//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Templates.Core.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Templates.Core.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not find file &apos;{0}&apos; to include the following changes. Review the code blocks to manually introduce the changes. .
        /// </summary>
        internal static string FailedMergePostActionFileNotFound {
            get {
                return ResourceManager.GetString("FailedMergePostActionFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not find the expected line `{0}` in file &apos;{1}&apos;. Review the code blocks to manually introduce the changes..
        /// </summary>
        internal static string FailedMergePostActionLineNotFound {
            get {
                return ResourceManager.GetString("FailedMergePostActionLineNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *This is a markdown file, to improve visualization you can install a Visual Studio extension for markdown files, for example: [Markdown Editor](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.MarkdownEditor)*.
        /// </summary>
        internal static string MarkdownHeader {
            get {
                return ResourceManager.GetString("MarkdownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is no merge target for file &apos;{0}&apos;.
        /// </summary>
        internal static string MergeFileNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("MergeFileNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Line {0} not found in file &apos;{1}&apos;.
        /// </summary>
        internal static string MergeLineNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("MergeLineNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adding items to project ....
        /// </summary>
        internal static string StatusAddingItems {
            get {
                return ResourceManager.GetString("StatusAddingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opening generated files ....
        /// </summary>
        internal static string StatusOpeningItems {
            get {
                return ResourceManager.GetString("StatusOpeningItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ## Conflicting files:.
        /// </summary>
        internal static string SyncInstructionsConflictingFiles {
            get {
                return ResourceManager.GetString("SyncInstructionsConflictingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a These files already exist in your project and were also generated as part of the new item.
        ///Please compare and make sure everything is in the right place..
        /// </summary>
        internal static string SyncInstructionsConflictingFilesDescription {
            get {
                return ResourceManager.GetString("SyncInstructionsConflictingFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please follow the indications to include the new item into you project:.
        /// </summary>
        internal static string SyncInstructionsDescription {
            get {
                return ResourceManager.GetString("SyncInstructionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steps to include new item generation.md.
        /// </summary>
        internal static string SyncInstructionsFileName {
            get {
                return ResourceManager.GetString("SyncInstructionsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a # Steps to include new item generation.
        /// </summary>
        internal static string SyncInstructionsHeader {
            get {
                return ResourceManager.GetString("SyncInstructionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ### Changes required in file &apos;{0}&apos;:.
        /// </summary>
        internal static string SyncInstructionsMergeFile {
            get {
                return ResourceManager.GetString("SyncInstructionsMergeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No preview file could be generated, the following changes could not be integrated: .
        /// </summary>
        internal static string SyncInstructionsMergeFileError {
            get {
                return ResourceManager.GetString("SyncInstructionsMergeFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preview the changes in: [{0}]({0}).
        /// </summary>
        internal static string SyncInstructionsMergeFilePreview {
            get {
                return ResourceManager.GetString("SyncInstructionsMergeFilePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ## Modified files:.
        /// </summary>
        internal static string SyncInstructionsModifiedFiles {
            get {
                return ResourceManager.GetString("SyncInstructionsModifiedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To integrate your new item with the existing project apply the following changes: .
        /// </summary>
        internal static string SyncInstructionsModifiedFilesDescription {
            get {
                return ResourceManager.GetString("SyncInstructionsModifiedFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ## New files:.
        /// </summary>
        internal static string SyncInstructionsNewFiles {
            get {
                return ResourceManager.GetString("SyncInstructionsNewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy and add the following files to your project:.
        /// </summary>
        internal static string SyncInstructionsNewFilesDescription {
            get {
                return ResourceManager.GetString("SyncInstructionsNewFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can find all referenced files in the temporary generation folder: {0}.
        /// </summary>
        internal static string SyncInstructionsTempFolder {
            get {
                return ResourceManager.GetString("SyncInstructionsTempFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ## Unchanged files:.
        /// </summary>
        internal static string SyncInstructionsUnchangedFiles {
            get {
                return ResourceManager.GetString("SyncInstructionsUnchangedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a These files already exist in your project, no action is necessary:.
        /// </summary>
        internal static string SyncInstructionsUnchangedFilesDescription {
            get {
                return ResourceManager.GetString("SyncInstructionsUnchangedFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ## Conflicting files:.
        /// </summary>
        internal static string SyncSummaryConflictingFiles {
            get {
                return ResourceManager.GetString("SyncSummaryConflictingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a These files already exist in your project and were also generated as part of the new item.
        ///Please compare and make sure everything is in the right place..
        /// </summary>
        internal static string SyncSummaryConflictingFilesDescription {
            get {
                return ResourceManager.GetString("SyncSummaryConflictingFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The following changes have been incorporated into your project:.
        /// </summary>
        internal static string SyncSummaryDescription {
            get {
                return ResourceManager.GetString("SyncSummaryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ## Failed changes in files:.
        /// </summary>
        internal static string SyncSummaryFailedMerges {
            get {
                return ResourceManager.GetString("SyncSummaryFailedMerges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Merges in the following files failed:.
        /// </summary>
        internal static string SyncSummaryFailedMergesDescription {
            get {
                return ResourceManager.GetString("SyncSummaryFailedMergesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GenerationSummary.md.
        /// </summary>
        internal static string SyncSummaryFileName {
            get {
                return ResourceManager.GetString("SyncSummaryFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a # Generation summary.
        /// </summary>
        internal static string SyncSummaryHeader {
            get {
                return ResourceManager.GetString("SyncSummaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ### Changes in file &apos;{0}&apos;:.
        /// </summary>
        internal static string SyncSummaryMergeFile {
            get {
                return ResourceManager.GetString("SyncSummaryMergeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The following changes could not be integrated:.
        /// </summary>
        internal static string SyncSummaryMergeFileError {
            get {
                return ResourceManager.GetString("SyncSummaryMergeFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See the final result: [{0}]({1}).
        /// </summary>
        internal static string SyncSummaryMergeFilePreview {
            get {
                return ResourceManager.GetString("SyncSummaryMergeFilePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ## Modified files:.
        /// </summary>
        internal static string SyncSummaryModifiedFiles {
            get {
                return ResourceManager.GetString("SyncSummaryModifiedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The following changes have been applied:.
        /// </summary>
        internal static string SyncSummaryModifiedFilesDescription {
            get {
                return ResourceManager.GetString("SyncSummaryModifiedFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ## New files:.
        /// </summary>
        internal static string SyncSummaryNewFiles {
            get {
                return ResourceManager.GetString("SyncSummaryNewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a These files have been added to your project..
        /// </summary>
        internal static string SyncSummaryNewFilesDescription {
            get {
                return ResourceManager.GetString("SyncSummaryNewFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ProjectFile.
        /// </summary>
        internal static string SyncSummaryProjectFile {
            get {
                return ResourceManager.GetString("SyncSummaryProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can find the files from the generation in the temporary generation folder: {0}.
        /// </summary>
        internal static string SyncSummaryTempFolder {
            get {
                return ResourceManager.GetString("SyncSummaryTempFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temp.
        /// </summary>
        internal static string SyncSummaryTempGenerationFile {
            get {
                return ResourceManager.GetString("SyncSummaryTempGenerationFile", resourceCulture);
            }
        }
    }
}
