// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TemplateStudioForUWP
{
    internal sealed partial class Vsix
    {
        public const string Id = "TemplateStudioForUWP.587647be-736e-4495-9a0f-d0d08148ee9b";
        public const string Name = "Template Studio for UWP";
        public const string Description = @"Template Studio accelerates the creation of new UWP apps using a wizard-based UI.";
        public const string Language = "en-US";
        public const string Version = "5.1";
        public const string Author = "Microsoft";
        public const string Tags = "Template Studio, UWP, XAML, MVVM";
    }
}
