// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TemplateStudioForUWP
{
    internal sealed partial class Vsix
    {
        public const string Id = "TemplateStudioForUWP.587647be-736e-4495-9a0f-d0d08148ee9b";
        public const string Name = "TemplateStudioForUWP";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Matt Lacey";
        public const string Tags = "";
    }
}
