// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TemplateStudioForWinUICs.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidTemplateStudioForWinUICsPackageString = "0348e2b7-f1a1-438d-a243-028ce03d87da";
        public static Guid guidTemplateStudioForWinUICsPackage = new Guid(guidTemplateStudioForWinUICsPackageString);

        public const string guidTemplateStudioForWinUICsUIContextString = "476eb402-260c-4efc-a311-1d8aede9a470";
        public static Guid guidTemplateStudioForWinUICsUIContext = new Guid(guidTemplateStudioForWinUICsUIContextString);

        public const string guidTemplateStudioForWinUICsPackageCmdSetString = "9808b482-559d-408f-8998-a00cbc1dfc79";
        public static Guid guidTemplateStudioForWinUICsPackageCmdSet = new Guid(guidTemplateStudioForWinUICsPackageCmdSetString);

        public const string guidImagesString = "4060629c-fd00-4d0f-8c97-92747bfb7f28";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int AddItemContextGroup = 0x0100;
        public const int AddItemContextMenu = 0x0200;
        public const int AddItemContextMenuGroup = 0x0300;
        public const int ToolsContextMenuGroup = 0x0350;
        public const int AddPageCommand = 0x0400;
        public const int AddFeatureCommand = 0x0500;
        public const int AddServiceCommand = 0x0600;
        public const int AddTestingCommand = 0x0700;
        public const int OpenTempFolder = 0x0800;
        public const int bmpFeature1 = 0x0001;
        public const int bmpFeature2 = 0x0002;
        public const int bmpFeature3 = 0x0003;
        public const int bmpFeature4 = 0x0004;
        public const int bmpPage1 = 0x0005;
        public const int bmpWTS = 0x0006;
        public const int bmpOpenTemp = 0x0007;
        public const int bmpService = 0x0008;
        public const int bmpTesting = 0x0009;
    }
}