parameters:
- name: Moniker
  type: string
- name: BuildConfiguration
  type: string
- name: BuildPlatform
  type: string
- name: Group
  type: string

jobs:
- job:
  displayName: Test
  timeoutInMinutes: 0
  pool:
    vmImage: windows-2022

  steps:
  - checkout: self
    clean: true
    submodules: recursive

  - task: NuGetToolInstaller@1
    displayName: Use NuGet
    inputs:
      checkLatest: true

  - task: NuGetCommand@2
    displayName: NuGet restore
    inputs:
      solution: code/TemplateStudio.sln

  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: code/TemplateStudio.${{ parameters.Moniker }}.slnf
      vsVersion: 17.0
      configuration: ${{ parameters.BuildConfiguration }}
      platform: ${{ parameters.BuildPlatform }}
      clean: true

  - task: BatchScript@1
    displayName: Set Agent Drive and Clean Test Folder
    inputs:
      filename: _build/SetAgentDriveAndCleanTestFolder.bat
      modifyEnvironment: true

  - task: PowerShell@1
    displayName: Test
    inputs:
      scriptName: _build/ParallelTestExecution.ps1
      arguments: -testRunner $(UserProfile)/.nuget/packages/xunit.runner.console/2.4.1/tools/net47/xunit.console.exe -testLibrary $(Build.SourcesDirectory)/code/test/TemplateStudioFor${{ parameters.Moniker }}.Tests/bin/Debug/TemplateStudioFor${{ parameters.Moniker }}.Tests.dll -traits 'Group=${{ parameters.Group }}' -outputDir $(Build.SourcesDirectory)

  - task: PublishTestResults@2
    displayName: Publish Test Results
    condition: succeededOrFailed()
    inputs:
      testRunner: XUnit
      testResultsFiles: '**/TEST-*.xml'