public ShellViewModel(INavigationService navigationServiceInstance)
^^^-searchabove-replacebelow-vvv
public ShellViewModel(INavigationService navigationServiceInstance, IUserDataService userDataService, IIdentityService identityService)