// <auto-generated>
// This file was created from a T4 template.
// Any manual changes will be overwritten.
// </auto-generated>
using System.Collections.Generic;

namespace TemplateStudioForWinUICs.Tests
{
    public partial class TemplateJsonValidationTests
    {
        public static IEnumerable<object[]> GetAllRelativeTemplateJsonFiles()
        {
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\AddConnectedAnimation\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\ExportParams.Page\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\ExportParams.Project\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Feature.AppNotifications\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Feature.SampleData\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Feature.SettingsStorage.Packaged\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Feature.SettingsStorage.Unpackaged\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Feature.ThemeSelection\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Page.AddBackCommand\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Page.AddCommandNS\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Page.AddViewModel\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Page.AddViewModelDetail\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Page.Settings.Packaged\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Page.Settings.Unpackaged\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Page.WebView\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Project\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Project.Blank\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Project.MenuBar\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Project.MenuBar.AddMenuItem\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Project.MenuBar.AddMenuItem.Settings\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Project.NavView\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Project.NavView.AddNavViewItem.Blank\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Project.NavView.AddNavViewItem.ContentGrid\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Project.NavView.AddNavViewItem.DataGrid\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Project.NavView.AddNavViewItem.ListDetails\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Project.NavView.AddNavViewItem.Settings\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\MT\Project.NavView.AddNavViewItem.WebView\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\_shared\Page.AddBackground.Blank\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\_shared\Page.AddTitle.Blank\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\_shared\Page.AddTitle.ContentGrid\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\_shared\Page.AddTitle.DataGrid\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\_shared\Page.AddTitle.Form\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\_shared\Page.AddTitle.Settings\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\_shared\Page.AddTitle.StringResources\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\_shared\Page.ListDetail.Blank.MenuBar\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\_shared\Page.ListDetail.NavView\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\_shared\Page.NavView.AddHeaderModeNever\.template.config\template.json" };
             yield return new object[] { @"..\..\TemplateStudioForWinUICs\Templates\_comp\_shared\Proj.Core.Platforms\.template.config\template.json" };
        }
    }
}

