public ApplicationHostService(INavigationService navigationService, IShellPage shellPage)
^^^-searchabove-replacebelow-vvv
public ApplicationHostService(INavigationService navigationService, IShellPage shellPage, IThemeSelectorService themeSelectorService)