public ShellViewModel(INavigationService navigationServiceInstance)
^^^-searchabove-replacebelow-vvv
public ShellViewModel(INavigationService navigationServiceInstance, IIdentityService identityService, IUserDataService userDataService)