name: 🐛 Bug report
description: Create a report to help us improve
labels: [bug]
body:
- type: textarea
  attributes:
    label: Describe the bug
    description: Please provide a clear and concise description of the bug.
  validations:
    required: true

- type: textarea
  attributes:
    label: To Reproduce
    description: "Steps to reproduce the behavior:"
    value: " 1. Go to '...'\n
2. Click on '....'\n
3. Scroll down to '....'\n
4. See error"

- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the bug here.

- type: checkboxes
  id: platforms
  attributes:
    label: "Applies to the following platforms:"
    options:
    - label: WinUI
    - label: WPF
    - label: UWP

- type: textarea
  attributes:
    label: About your setup
    description: Please provide the following to help us investigate.
    value: " - Visual Studio Version:  \n
- Template Studio Wizard Version: \n
- Windows Build: "