//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Templates.Extension.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Templates.Extension.Resources.StringRes", typeof(StringRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Feature.
        /// </summary>
        public static string AddFeatureAction {
            get {
                return ResourceManager.GetString("AddFeatureAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Page.
        /// </summary>
        public static string AddPageAction {
            get {
                return ResourceManager.GetString("AddPageAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Project.
        /// </summary>
        public static string AddProjectAction {
            get {
                return ResourceManager.GetString("AddProjectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service.
        /// </summary>
        public static string AddServiceAction {
            get {
                return ResourceManager.GetString("AddServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Testing.
        /// </summary>
        public static string AddTestingAction {
            get {
                return ResourceManager.GetString("AddTestingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Template Studio: {0}.
        /// </summary>
        public static string UIMessageBoxTitlePattern {
            get {
                return ResourceManager.GetString("UIMessageBoxTitlePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Template Studio: {0}.
        /// </summary>
        public static string UIStatusMsgPattern {
            get {
                return ResourceManager.GetString("UIStatusMsgPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Exception.\n{0}.
        /// </summary>
        public static string UnexpectedExPattern {
            get {
                return ResourceManager.GetString("UnexpectedExPattern", resourceCulture);
            }
        }
    }
}
