// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TemplateStudioForWinUICpp
{
    internal sealed partial class Vsix
    {
        public const string Id = "TemplateStudioForWinUICpp.98f70df4-a2c9-4ae2-86d6-a9e2b5bf05c6";
        public const string Name = "TemplateStudioForWinUICpp";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Matt Lacey";
        public const string Tags = "";
    }
}
