//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Templates.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Templates.UI.Resources.StringRes", typeof(StringRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name.
        /// </summary>
        public static string EditTemplateDescription {
            get {
                return ResourceManager.GetString("EditTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong :-(.
        /// </summary>
        public static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not possible to create a project without Home Page.
        /// </summary>
        public static string ErrorNoHomePage {
            get {
                return ResourceManager.GetString("ErrorNoHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error syncing templates. See output for more details..
        /// </summary>
        public static string ErrorSync {
            get {
                return ResourceManager.GetString("ErrorSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View problem details.
        /// </summary>
        public static string ErrorViewProblemDetails {
            get {
                return ResourceManager.GetString("ErrorViewProblemDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular dependency detected on template {0} with {1}..
        /// </summary>
        public static string ExceptionDependencyCircularReference {
            get {
                return ResourceManager.GetString("ExceptionDependencyCircularReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid dependency item {0}. Dependencies have to be configured as multpleInstance = false..
        /// </summary>
        public static string ExceptionDependencyMultipleInstance {
            get {
                return ResourceManager.GetString("ExceptionDependencyMultipleInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency template {0} not found for framework {1}..
        /// </summary>
        public static string ExceptionDependencyNotFound {
            get {
                return ResourceManager.GetString("ExceptionDependencyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid dependency item {0}. Dependency items must be of type Page or Feature..
        /// </summary>
        public static string ExceptionDependencyType {
            get {
                return ResourceManager.GetString("ExceptionDependencyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template &apos;{0}&apos;, name: &apos;{1}&apos;, reason: &apos;{2}&apos;.
        /// </summary>
        public static string ExceptionGenerating {
            get {
                return ResourceManager.GetString("ExceptionGenerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout template {0} not found for framework {1}..
        /// </summary>
        public static string ExceptionLayoutNotFound {
            get {
                return ResourceManager.GetString("ExceptionLayoutNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid layout item {0}. Layout items must be of type Page or Feature..
        /// </summary>
        public static string ExceptionLayoutType {
            get {
                return ResourceManager.GetString("ExceptionLayoutType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding &apos;{0}&apos; feature to project....
        /// </summary>
        public static string GeneratingFeatureMessage {
            get {
                return ResourceManager.GetString("GeneratingFeatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding &apos;{0}&apos; page to project....
        /// </summary>
        public static string GeneratingPageMessage {
            get {
                return ResourceManager.GetString("GeneratingPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating project &apos;{0}&apos;....
        /// </summary>
        public static string GeneratingProjectMessage {
            get {
                return ResourceManager.GetString("GeneratingProjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features ({0}) - Add multiple.
        /// </summary>
        public static string GroupFeaturesHeader_SF {
            get {
                return ResourceManager.GetString("GroupFeaturesHeader_SF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework ({0}) - Pick one.
        /// </summary>
        public static string GroupFrameworkHeader_SF {
            get {
                return ResourceManager.GetString("GroupFrameworkHeader_SF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages ({0}) - Add multiple.
        /// </summary>
        public static string GroupPagesHeader_SF {
            get {
                return ResourceManager.GetString("GroupPagesHeader_SF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Type.
        /// </summary>
        public static string GroupProjectType {
            get {
                return ResourceManager.GetString("GroupProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Type ({0}) - Pick one.
        /// </summary>
        public static string GroupProjectTypeHeader_SF {
            get {
                return ResourceManager.GetString("GroupProjectTypeHeader_SF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string InfoModalAuthor {
            get {
                return ResourceManager.GetString("InfoModalAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies:.
        /// </summary>
        public static string InfoModalDependencies {
            get {
                return ResourceManager.GetString("InfoModalDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses:.
        /// </summary>
        public static string InfoModalLicenses {
            get {
                return ResourceManager.GetString("InfoModalLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string InfoModalVersion {
            get {
                return ResourceManager.GetString("InfoModalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less detail.
        /// </summary>
        public static string LessDetail {
            get {
                return ResourceManager.GetString("LessDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading available templates....
        /// </summary>
        public static string LoadingTemplatesText {
            get {
                return ResourceManager.GetString("LoadingTemplatesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made by {0}.
        /// </summary>
        public static string MadeBy {
            get {
                return ResourceManager.GetString("MadeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More detail.
        /// </summary>
        public static string MoreDetail {
            get {
                return ResourceManager.GetString("MoreDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content available.
        /// </summary>
        public static string NoContentText {
            get {
                return ResourceManager.GetString("NoContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select project type and framework.
        /// </summary>
        public static string ProjectSetupTitle {
            get {
                return ResourceManager.GetString("ProjectSetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select pages and features.
        /// </summary>
        public static string ProjectTemplatesTitle {
            get {
                return ResourceManager.GetString("ProjectTemplatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have changed your project type or framework selection. If you continue you will lose all pages and features added previously. To conserve pages and features, you can go back to your original selection ({0}, {1})..
        /// </summary>
        public static string ResetSelection {
            get {
                return ResourceManager.GetString("ResetSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset selection.
        /// </summary>
        public static string ResetSelectionTitle {
            get {
                return ResourceManager.GetString("ResetSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring packages....
        /// </summary>
        public static string RestoringMessage {
            get {
                return ResourceManager.GetString("RestoringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string StatusAdquired {
            get {
                return ResourceManager.GetString("StatusAdquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for template updates....
        /// </summary>
        public static string StatusAdquiring {
            get {
                return ResourceManager.GetString("StatusAdquiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no templates content available for the current wizard version. Please ensure you have connectivity and restart the wizard again..
        /// </summary>
        public static string StatusLowerVersionContent {
            get {
                return ResourceManager.GetString("StatusLowerVersionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard incompatible with templates content.
        /// </summary>
        public static string StatusLowerVersionTitle {
            get {
                return ResourceManager.GetString("StatusLowerVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update to the templates is available. Update the extension to get the latest content..
        /// </summary>
        public static string StatusOverVersionContent {
            get {
                return ResourceManager.GetString("StatusOverVersionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no content available for this extension version. Update the extension to access to the latest content..
        /// </summary>
        public static string StatusOverVersionNoContent {
            get {
                return ResourceManager.GetString("StatusOverVersionNoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard update available.
        /// </summary>
        public static string StatusOverVersionTitle {
            get {
                return ResourceManager.GetString("StatusOverVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates ready.
        /// </summary>
        public static string StatusPrepared {
            get {
                return ResourceManager.GetString("StatusPrepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing templates for first use....
        /// </summary>
        public static string StatusPreparing {
            get {
                return ResourceManager.GetString("StatusPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates updated.
        /// </summary>
        public static string StatusUpdated {
            get {
                return ResourceManager.GetString("StatusUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating templates....
        /// </summary>
        public static string StatusUpdating {
            get {
                return ResourceManager.GetString("StatusUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string SummaryFeaturesTitle {
            get {
                return ResourceManager.GetString("SummaryFeaturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework.
        /// </summary>
        public static string SummaryFrameworkTitle {
            get {
                return ResourceManager.GetString("SummaryFrameworkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string SummaryLicenseTitle {
            get {
                return ResourceManager.GetString("SummaryLicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None Selected.
        /// </summary>
        public static string SummaryNoFeatures {
            get {
                return ResourceManager.GetString("SummaryNoFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string SummaryNoLicenses {
            get {
                return ResourceManager.GetString("SummaryNoLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None Selected.
        /// </summary>
        public static string SummaryNoPages {
            get {
                return ResourceManager.GetString("SummaryNoPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string SummaryOptionDelete {
            get {
                return ResourceManager.GetString("SummaryOptionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string SummaryOptionMoveDown {
            get {
                return ResourceManager.GetString("SummaryOptionMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string SummaryOptionMoveUp {
            get {
                return ResourceManager.GetString("SummaryOptionMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string SummaryOptionRename {
            get {
                return ResourceManager.GetString("SummaryOptionRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as home.
        /// </summary>
        public static string SummaryOptionSetAsHome {
            get {
                return ResourceManager.GetString("SummaryOptionSetAsHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string SummaryPagesTitle {
            get {
                return ResourceManager.GetString("SummaryPagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Type.
        /// </summary>
        public static string SummaryProjectTypeTitle {
            get {
                return ResourceManager.GetString("SummaryProjectTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By continuing, you agree to the terms of all the licenses in the licensing section above..
        /// </summary>
        public static string SummaryTerms {
            get {
                return ResourceManager.GetString("SummaryTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string SummaryTitle {
            get {
                return ResourceManager.GetString("SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Lifecycle.
        /// </summary>
        public static string TemplateGroup_ApplicationLifecycle {
            get {
                return ResourceManager.GetString("TemplateGroup_ApplicationLifecycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Work.
        /// </summary>
        public static string TemplateGroup_BackgroundWork {
            get {
                return ResourceManager.GetString("TemplateGroup_BackgroundWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interaction.
        /// </summary>
        public static string TemplateGroup_UserInteraction {
            get {
                return ResourceManager.GetString("TemplateGroup_UserInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates version:.
        /// </summary>
        public static string TemplatesVersion {
            get {
                return ResourceManager.GetString("TemplatesVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature.
        /// </summary>
        public static string TemplateTypeFeature {
            get {
                return ResourceManager.GetString("TemplateTypeFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework.
        /// </summary>
        public static string TemplateTypeFramework {
            get {
                return ResourceManager.GetString("TemplateTypeFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string TemplateTypePage {
            get {
                return ResourceManager.GetString("TemplateTypePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project type.
        /// </summary>
        public static string TemplateTypeProjectType {
            get {
                return ResourceManager.GetString("TemplateTypeProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Template Studio.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Template Studio: {0}.
        /// </summary>
        public static string UIMessageBoxTitlePattern {
            get {
                return ResourceManager.GetString("UIMessageBoxTitlePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable add project items. Ensure you have the required SDK..
        /// </summary>
        public static string UnableAddItemsToProject {
            get {
                return ResourceManager.GetString("UnableAddItemsToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add the project to the solution because is not ready. Ensure you have the expected SDK installed..
        /// </summary>
        public static string UnableAddProjectToSolution {
            get {
                return ResourceManager.GetString("UnableAddProjectToSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to refresh the project. Try to refresh it manually..
        /// </summary>
        public static string UnableToRefreshProject {
            get {
                return ResourceManager.GetString("UnableToRefreshProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already exists.
        /// </summary>
        public static string ValidationError_AlreadyExists {
            get {
                return ResourceManager.GetString("ValidationError_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only alphanumeric and &apos;-&apos; characters are allowed.
        /// </summary>
        public static string ValidationError_BadFormat {
            get {
                return ResourceManager.GetString("ValidationError_BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not remove {0} because {1} {2} depends on it..
        /// </summary>
        public static string ValidationError_CanNotRemoveTemplate_SF {
            get {
                return ResourceManager.GetString("ValidationError_CanNotRemoveTemplate_SF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty.
        /// </summary>
        public static string ValidationError_Empty {
            get {
                return ResourceManager.GetString("ValidationError_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set a custom name.
        /// </summary>
        public static string ValidationError_RenameNotAllowed {
            get {
                return ResourceManager.GetString("ValidationError_RenameNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is reserved.
        /// </summary>
        public static string ValidationError_ReservedName {
            get {
                return ResourceManager.GetString("ValidationError_ReservedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard version:.
        /// </summary>
        public static string WizardVersion {
            get {
                return ResourceManager.GetString("WizardVersion", resourceCulture);
            }
        }
    }
}
