//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Templates.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Templates.UI.Resources.StringRes", typeof(StringRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code viewer.
        /// </summary>
        public static string AccessibilityCodeViewerControl {
            get {
                return ResourceManager.GetString("AccessibilityCodeViewerControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design patterns.
        /// </summary>
        public static string AccessibilityDesignPatternList {
            get {
                return ResourceManager.GetString("AccessibilityDesignPatternList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page name.
        /// </summary>
        public static string AccessibilityEditPageItem {
            get {
                return ResourceManager.GetString("AccessibilityEditPageItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error text description.
        /// </summary>
        public static string AccessibilityErrorDialogDescriptionTextboxName {
            get {
                return ResourceManager.GetString("AccessibilityErrorDialogDescriptionTextboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation menu.
        /// </summary>
        public static string AccessibilityNavigationMenu {
            get {
                return ResourceManager.GetString("AccessibilityNavigationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New item file icon.
        /// </summary>
        public static string AccessibilityNewItemFileIcon {
            get {
                return ResourceManager.GetString("AccessibilityNewItemFileIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification panel.
        /// </summary>
        public static string AccessibilityNotificationPanel {
            get {
                return ResourceManager.GetString("AccessibilityNotificationPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project types.
        /// </summary>
        public static string AccessibilityProjectTypesList {
            get {
                return ResourceManager.GetString("AccessibilityProjectTypesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential flow control.
        /// </summary>
        public static string AccessibilitySequentialFlowControl {
            get {
                return ResourceManager.GetString("AccessibilitySequentialFlowControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates list.
        /// </summary>
        public static string AccessibilityTemplatesList {
            get {
                return ResourceManager.GetString("AccessibilityTemplatesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User selection pages.
        /// </summary>
        public static string AccessibilityUserSelectionPageList {
            get {
                return ResourceManager.GetString("AccessibilityUserSelectionPageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add features.
        /// </summary>
        public static string AddFeaturesTitle {
            get {
                return ResourceManager.GetString("AddFeaturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add pages.
        /// </summary>
        public static string AddPagesTitle {
            get {
                return ResourceManager.GetString("AddPagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add services.
        /// </summary>
        public static string AddServiceTitle {
            get {
                return ResourceManager.GetString("AddServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add testing.
        /// </summary>
        public static string AddTestingTitle {
            get {
                return ResourceManager.GetString("AddTestingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaking changes.
        /// </summary>
        public static string BreakingChanges {
            get {
                return ResourceManager.GetString("BreakingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have detected incompatibilities between your project and the last templates version. Please review the changes:.
        /// </summary>
        public static string BreakingChangesDialogMessage {
            get {
                return ResourceManager.GetString("BreakingChangesDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composition tool.
        /// </summary>
        public static string ButtonCompositionTool {
            get {
                return ResourceManager.GetString("ButtonCompositionTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string ButtonDetails {
            get {
                return ResourceManager.GetString("ButtonDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of {0}.
        /// </summary>
        public static string ButtonDetailsHelpText {
            get {
                return ResourceManager.GetString("ButtonDetailsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh templates cache.
        /// </summary>
        public static string ButtonRefreshTemplatesCache {
            get {
                return ResourceManager.GetString("ButtonRefreshTemplatesCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string ButtonRemove {
            get {
                return ResourceManager.GetString("ButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not merge changes (generate in a temp folder)..
        /// </summary>
        public static string ChangesSummaryCheckBoxText {
            get {
                return ResourceManager.GetString("ChangesSummaryCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting files.
        /// </summary>
        public static string ChangesSummaryGroupConflictingFiles {
            get {
                return ResourceManager.GetString("ChangesSummaryGroupConflictingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file already exists in your project but was also generated as part of the new item. Your current file will not be modified or overwritten. Please compare and make sure everything is the right place. If needed, you can access to the generated file after finishing..
        /// </summary>
        public static string ChangesSummaryGroupConflictingFilesDescription {
            get {
                return ResourceManager.GetString("ChangesSummaryGroupConflictingFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting styles files.
        /// </summary>
        public static string ChangesSummaryGroupConflictingStylesFiles {
            get {
                return ResourceManager.GetString("ChangesSummaryGroupConflictingStylesFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are not able to introduce the styles in the resource dictionary..
        /// </summary>
        public static string ChangesSummaryGroupConflictingStylesFilesDescription {
            get {
                return ResourceManager.GetString("ChangesSummaryGroupConflictingStylesFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified files.
        /// </summary>
        public static string ChangesSummaryGroupModifiedFiles {
            get {
                return ResourceManager.GetString("ChangesSummaryGroupModifiedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file will be modified to include required content..
        /// </summary>
        public static string ChangesSummaryGroupModifiedFilesDescription {
            get {
                return ResourceManager.GetString("ChangesSummaryGroupModifiedFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New files.
        /// </summary>
        public static string ChangesSummaryGroupNewFiles {
            get {
                return ResourceManager.GetString("ChangesSummaryGroupNewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file will be added as new file to your project..
        /// </summary>
        public static string ChangesSummaryGroupNewFilesDescription {
            get {
                return ResourceManager.GetString("ChangesSummaryGroupNewFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchanged files.
        /// </summary>
        public static string ChangesSummaryGroupUnchangedFiles {
            get {
                return ResourceManager.GetString("ChangesSummaryGroupUnchangedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file already exists in your project and no further action is necessary. The file will remain unchanged..
        /// </summary>
        public static string ChangesSummaryGroupUnchangedFilesDescription {
            get {
                return ResourceManager.GetString("ChangesSummaryGroupUnchangedFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning files.
        /// </summary>
        public static string ChangesSummaryGroupWarningFiles {
            get {
                return ResourceManager.GetString("ChangesSummaryGroupWarningFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are not able to introduce the modifications required. If needed, you can access the generated file after finishing..
        /// </summary>
        public static string ChangesSummaryGroupWarningFilesDescription {
            get {
                return ResourceManager.GetString("ChangesSummaryGroupWarningFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more info.
        /// </summary>
        public static string ChangesSummaryMoreInfoLink {
            get {
                return ResourceManager.GetString("ChangesSummaryMoreInfoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding items to project {0}.
        /// </summary>
        public static string ErrorAddingItemsToProject {
            get {
                return ResourceManager.GetString("ErrorAddingItemsToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding project {0}.
        /// </summary>
        public static string ErrorAddingProject {
            get {
                return ResourceManager.GetString("ErrorAddingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding references between projects.
        /// </summary>
        public static string ErrorAddingReferencesBetweenProjects {
            get {
                return ResourceManager.GetString("ErrorAddingReferencesBetweenProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding sdks to project {0}..
        /// </summary>
        public static string ErrorAddingSdksToProject {
            get {
                return ResourceManager.GetString("ErrorAddingSdksToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        public static string ErrorDialogShowDetails {
            get {
                return ResourceManager.GetString("ErrorDialogShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong :-(.
        /// </summary>
        public static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Requirement Type {0}.
        /// </summary>
        public static string ErrorInvalidRequirementType {
            get {
                return ResourceManager.GetString("ErrorInvalidRequirementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install-Package -Id {0} -Version {1}.
        /// </summary>
        public static string ErrorMissingNugetPackagesInstallTemplate {
            get {
                return ResourceManager.GetString("ErrorMissingNugetPackagesInstallTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some NuGet packages could not be added to your project {0}. This could have been caused if you were offline. 
        ///Please verify the following list of packages needed by your project&apos;s code and manually add the missing packages: 
        ///
        ///{1}.
        /// </summary>
        public static string ErrorMissingNugetPackagesTemplate {
            get {
                return ResourceManager.GetString("ErrorMissingNugetPackagesTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find project {0}.
        /// </summary>
        public static string ErrorUnableGetProjectByPath {
            get {
                return ResourceManager.GetString("ErrorUnableGetProjectByPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set default solution configuration.
        /// </summary>
        public static string ErrorUnableToSetDefaultConfiguration {
            get {
                return ResourceManager.GetString("ErrorUnableToSetDefaultConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error collapsing the solution tree. Ex:.
        /// </summary>
        public static string ErrorVsGenShellCollapseSolutionItemsMessage {
            get {
                return ResourceManager.GetString("ErrorVsGenShellCollapseSolutionItemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error showing status message. Ex:.
        /// </summary>
        public static string ErrorVsGenShellShowStatusBarMessageMessage {
            get {
                return ResourceManager.GetString("ErrorVsGenShellShowStatusBarMessageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in a new browser tab.
        /// </summary>
        public static string ExternalHyperlinkTooltipMessage {
            get {
                return ResourceManager.GetString("ExternalHyperlinkTooltipMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPRECATED.
        /// </summary>
        public static string Flag_Deprecated {
            get {
                return ResourceManager.GetString("Flag_Deprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a design pattern.
        /// </summary>
        public static string FrameworkTitle {
            get {
                return ResourceManager.GetString("FrameworkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press enter to add {0}.
        /// </summary>
        public static string HelpTextPressEnterToAddItem {
            get {
                return ResourceManager.GetString("HelpTextPressEnterToAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higher version required.
        /// </summary>
        public static string InfoDialogInvalidVersionTitle {
            get {
                return ResourceManager.GetString("InfoDialogInvalidVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPF with .NET Core project creation requires Visual Studio 2019 Update 3 or higher..
        /// </summary>
        public static string InfoDialogInvalidVSVersionForWPF {
            get {
                return ResourceManager.GetString("InfoDialogInvalidVSVersionForWPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing workload.
        /// </summary>
        public static string InfoDialogMissingWorkloadTitle {
            get {
                return ResourceManager.GetString("InfoDialogMissingWorkloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More info.
        /// </summary>
        public static string InfoDialogMoreInfoLinkText {
            get {
                return ResourceManager.GetString("InfoDialogMoreInfoLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to install the following workloads to create a {0} project: {1} .
        /// </summary>
        public static string InfoDialogRequiredWorkloadNotFoundMessage {
            get {
                return ResourceManager.GetString("InfoDialogRequiredWorkloadNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already part of your project. Please choose another feature..
        /// </summary>
        public static string NewItemHasNoChangesFeature {
            get {
                return ResourceManager.GetString("NewItemHasNoChangesFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already part of your project. Please choose another page..
        /// </summary>
        public static string NewItemHasNoChangesPage {
            get {
                return ResourceManager.GetString("NewItemHasNoChangesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already part of your project. Please choose another service..
        /// </summary>
        public static string NewItemHasNoChangesService {
            get {
                return ResourceManager.GetString("NewItemHasNoChangesService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already part of your project. Please choose another testing project..
        /// </summary>
        public static string NewItemHasNoChangesTesting {
            get {
                return ResourceManager.GetString("NewItemHasNoChangesTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template selection.
        /// </summary>
        public static string NewItemStepOne {
            get {
                return ResourceManager.GetString("NewItemStepOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes summary.
        /// </summary>
        public static string NewItemStepTwo {
            get {
                return ResourceManager.GetString("NewItemStepTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string NewItemTemplateDetailsDependenciesSectionTitle {
            get {
                return ResourceManager.GetString("NewItemTemplateDetailsDependenciesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string NewItemTemplateDetailsLicensesSectionTitle {
            get {
                return ResourceManager.GetString("NewItemTemplateDetailsLicensesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NewItemTemplateDetailsNameSectionTitle {
            get {
                return ResourceManager.GetString("NewItemTemplateDetailsNameSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Details.
        /// </summary>
        public static string NewItemTemplateDetailsTitle {
            get {
                return ResourceManager.GetString("NewItemTemplateDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New feature.
        /// </summary>
        public static string NewItemTitleFeature {
            get {
                return ResourceManager.GetString("NewItemTitleFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New page.
        /// </summary>
        public static string NewItemTitlePage {
            get {
                return ResourceManager.GetString("NewItemTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New service.
        /// </summary>
        public static string NewItemTitleService {
            get {
                return ResourceManager.GetString("NewItemTitleService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New testing project.
        /// </summary>
        public static string NewItemTitleTesting {
            get {
                return ResourceManager.GetString("NewItemTitleTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design pattern.
        /// </summary>
        public static string NewProjectStepDesignPattern {
            get {
                return ResourceManager.GetString("NewProjectStepDesignPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string NewProjectStepFeatures {
            get {
                return ResourceManager.GetString("NewProjectStepFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string NewProjectStepPages {
            get {
                return ResourceManager.GetString("NewProjectStepPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project type.
        /// </summary>
        public static string NewProjectStepProjectType {
            get {
                return ResourceManager.GetString("NewProjectStepProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string NewProjectStepServices {
            get {
                return ResourceManager.GetString("NewProjectStepServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        public static string NewProjectStepTesting {
            get {
                return ResourceManager.GetString("NewProjectStepTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Universal Windows Platform app.
        /// </summary>
        public static string NewProjectTitleUWP {
            get {
                return ResourceManager.GetString("NewProjectTitleUWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New WinUI3 Desktop app.
        /// </summary>
        public static string NewProjectTitleWinUI {
            get {
                return ResourceManager.GetString("NewProjectTitleWinUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New WPF app.
        /// </summary>
        public static string NewProjectTitleWPF {
            get {
                return ResourceManager.GetString("NewProjectTitleWPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no content available..
        /// </summary>
        public static string NoContentPanelMessage {
            get {
                return ResourceManager.GetString("NoContentPanelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not add **{0}** because the following templates are not compatible: {1}..
        /// </summary>
        public static string NotificationAdditionError_Exclusion {
            get {
                return ResourceManager.GetString("NotificationAdditionError_Exclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not add **{0}** because it is requires one of the following templates to be added first: {1}.
        /// </summary>
        public static string NotificationAdditionError_Requirement {
            get {
                return ResourceManager.GetString("NotificationAdditionError_Requirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following versions are missing, please install them and restart Visual Studio: {0}.
        /// </summary>
        public static string NotificationMissingVersions {
            get {
                return ResourceManager.GetString("NotificationMissingVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not remove **{0}** because these templates depend on it: {1}.
        /// </summary>
        public static string NotificationRemoveError_Dependency {
            get {
                return ResourceManager.GetString("NotificationRemoveError_Dependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not remove **{0}** because it is required for the selected project type..
        /// </summary>
        public static string NotificationRemoveError_ReadOnly {
            get {
                return ResourceManager.GetString("NotificationRemoveError_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not remove **{0}** because it is required for: {1}.
        /// </summary>
        public static string NotificationRemoveError_Requirement {
            get {
                return ResourceManager.GetString("NotificationRemoveError_Requirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error refreshing templates. See output window for more details..
        /// </summary>
        public static string NotificationSyncError_Refresh {
            get {
                return ResourceManager.GetString("NotificationSyncError_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are new templates available (v{0}). Downloading… {1}%.
        /// </summary>
        public static string NotificationSyncStatus_Acquiring {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_Acquiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string NotificationSyncStatus_CheckingForUpdates {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading templates (v{0}). We&apos;ll try later again..
        /// </summary>
        public static string NotificationSyncStatus_ErrorAcquiring {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_ErrorAcquiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Template Studio Version {0} is available. Update the extension to enjoy the latest features..
        /// </summary>
        public static string NotificationSyncStatus_NewWizardVersionAvailable {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_NewWizardVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing templates (v{0})... {1}%.
        /// </summary>
        public static string NotificationSyncStatus_Preparing {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates updated..
        /// </summary>
        public static string NotificationSyncStatus_Updated {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing templates cache….
        /// </summary>
        public static string NotificationSyncStatus_Updating {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already exists.
        /// </summary>
        public static string NotificationValidationError_AlreadyExists {
            get {
                return ResourceManager.GetString("NotificationValidationError_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only alphanumeric and &apos;_&apos; characters are allowed.
        /// </summary>
        public static string NotificationValidationError_BadFormat {
            get {
                return ResourceManager.GetString("NotificationValidationError_BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty.
        /// </summary>
        public static string NotificationValidationError_Empty {
            get {
                return ResourceManager.GetString("NotificationValidationError_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot end with &apos;Page&apos; as this will be automatically added. [More info about naming.]({0}WTSNaming.md).
        /// </summary>
        public static string NotificationValidationError_PageSuffix {
            get {
                return ResourceManager.GetString("NotificationValidationError_PageSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project name does not match the project folder name. Please adjust to ensure a correct generation..
        /// </summary>
        public static string NotificationValidationError_ProjectNameAndPathDoNotMatch {
            get {
                return ResourceManager.GetString("NotificationValidationError_ProjectNameAndPathDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegEx validation {0} failed..
        /// </summary>
        public static string NotificationValidationError_Regex {
            get {
                return ResourceManager.GetString("NotificationValidationError_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is reserved.
        /// </summary>
        public static string NotificationValidationError_ReservedName {
            get {
                return ResourceManager.GetString("NotificationValidationError_ReservedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that &apos;Page&apos; will be added to the end of the specified name. [More info about naming.]({0}WTSNaming.md).
        /// </summary>
        public static string NotificationValidationWarning_ViewSuffix {
            get {
                return ResourceManager.GetString("NotificationValidationWarning_ViewSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are unable to find the project configuration metadata in the Package.appxmanifest file. Can you please provide the project configuration you selected when the project was created?.
        /// </summary>
        public static string ProjectConfigurationDescriptionText {
            get {
                return ResourceManager.GetString("ProjectConfigurationDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select design pattern:.
        /// </summary>
        public static string ProjectConfigurationSelectFramework {
            get {
                return ResourceManager.GetString("ProjectConfigurationSelectFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select platform.
        /// </summary>
        public static string ProjectConfigurationSelectPlatform {
            get {
                return ResourceManager.GetString("ProjectConfigurationSelectPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select project type:.
        /// </summary>
        public static string ProjectConfigurationSelectProjectType {
            get {
                return ResourceManager.GetString("ProjectConfigurationSelectProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose project configuration.
        /// </summary>
        public static string ProjectConfigurationTitleText {
            get {
                return ResourceManager.GetString("ProjectConfigurationTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report issue.
        /// </summary>
        public static string ProjectDetailsAboutSectionIssuesLink {
            get {
                return ResourceManager.GetString("ProjectDetailsAboutSectionIssuesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Template Studio.
        /// </summary>
        public static string ProjectDetailsAboutSectionLink {
            get {
                return ResourceManager.GetString("ProjectDetailsAboutSectionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates version:.
        /// </summary>
        public static string ProjectDetailsAboutSectionTemplatesVersion {
            get {
                return ResourceManager.GetString("ProjectDetailsAboutSectionTemplatesVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ProjectDetailsAboutSectionTitle {
            get {
                return ResourceManager.GetString("ProjectDetailsAboutSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard version:.
        /// </summary>
        public static string ProjectDetailsAboutSectionWizardVersion {
            get {
                return ResourceManager.GetString("ProjectDetailsAboutSectionWizardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string ProjectDetailsFeaturesSectionTitle {
            get {
                return ResourceManager.GetString("ProjectDetailsFeaturesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have changed your design pattern selection. The pages and features you have selected will be lost. Do you want to continue?.
        /// </summary>
        public static string ProjectDetailsFrameworkResetDescription {
            get {
                return ResourceManager.GetString("ProjectDetailsFrameworkResetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design pattern changed.
        /// </summary>
        public static string ProjectDetailsFrameworkResetTitle {
            get {
                return ResourceManager.GetString("ProjectDetailsFrameworkResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design pattern.
        /// </summary>
        public static string ProjectDetailsFrameworkSectionTitle {
            get {
                return ResourceManager.GetString("ProjectDetailsFrameworkSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string ProjectDetailsLicensesSectionTitle {
            get {
                return ResourceManager.GetString("ProjectDetailsLicensesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string ProjectDetailsPagesSectionTitle {
            get {
                return ResourceManager.GetString("ProjectDetailsPagesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have changed your project type selection. The templates you have selected will be lost. Do you want to continue?.
        /// </summary>
        public static string ProjectDetailsProjectTypeResetDescription {
            get {
                return ResourceManager.GetString("ProjectDetailsProjectTypeResetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project type changed.
        /// </summary>
        public static string ProjectDetailsProjectTypeResetTitle {
            get {
                return ResourceManager.GetString("ProjectDetailsProjectTypeResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project type.
        /// </summary>
        public static string ProjectDetailsProjectTypeSectionTitle {
            get {
                return ResourceManager.GetString("ProjectDetailsProjectTypeSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string ProjectDetailsServicesSectionTitle {
            get {
                return ResourceManager.GetString("ProjectDetailsServicesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        public static string ProjectDetailsTestingSectionTitle {
            get {
                return ResourceManager.GetString("ProjectDetailsTestingSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your project details.
        /// </summary>
        public static string ProjectDetailsTitle {
            get {
                return ResourceManager.GetString("ProjectDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a project type.
        /// </summary>
        public static string ProjectTypeTitle {
            get {
                return ResourceManager.GetString("ProjectTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ctrl+up arrow or ctrl+down arrow to change page order.
        /// </summary>
        public static string ReorderPageHelpText {
            get {
                return ResourceManager.GetString("ReorderPageHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string SeparatorOr {
            get {
                return ResourceManager.GetString("SeparatorOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding {0} to project ....
        /// </summary>
        public static string StatusAddingItem {
            get {
                return ResourceManager.GetString("StatusAddingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding NuGet package {0} to project ....
        /// </summary>
        public static string StatusAddingNuget {
            get {
                return ResourceManager.GetString("StatusAddingNuget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding project {0} to solution....
        /// </summary>
        public static string StatusAddingProject {
            get {
                return ResourceManager.GetString("StatusAddingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding references between projects....
        /// </summary>
        public static string StatusAddingProjectReferences {
            get {
                return ResourceManager.GetString("StatusAddingProjectReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Windows Template Studio project....
        /// </summary>
        public static string StatusBarCreatingProject {
            get {
                return ResourceManager.GetString("StatusBarCreatingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation finished.
        /// </summary>
        public static string StatusBarGenerationFinished {
            get {
                return ResourceManager.GetString("StatusBarGenerationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new feature cancelled.
        /// </summary>
        public static string StatusBarNewItemAddFeatureCancelled {
            get {
                return ResourceManager.GetString("StatusBarNewItemAddFeatureCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature {0} successfully added.
        /// </summary>
        public static string StatusBarNewItemAddFeatureSuccess {
            get {
                return ResourceManager.GetString("StatusBarNewItemAddFeatureSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new page cancelled.
        /// </summary>
        public static string StatusBarNewItemAddPageCancelled {
            get {
                return ResourceManager.GetString("StatusBarNewItemAddPageCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} successfully added.
        /// </summary>
        public static string StatusBarNewItemAddPageSuccess {
            get {
                return ResourceManager.GetString("StatusBarNewItemAddPageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new service cancelled.
        /// </summary>
        public static string StatusBarNewItemAddServiceCancelled {
            get {
                return ResourceManager.GetString("StatusBarNewItemAddServiceCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} successfully added.
        /// </summary>
        public static string StatusBarNewItemAddServiceSuccess {
            get {
                return ResourceManager.GetString("StatusBarNewItemAddServiceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new testing project cancelled.
        /// </summary>
        public static string StatusBarNewItemAddTestingCancelled {
            get {
                return ResourceManager.GetString("StatusBarNewItemAddTestingCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing project {0} successfully added.
        /// </summary>
        public static string StatusBarNewItemAddTestingSuccess {
            get {
                return ResourceManager.GetString("StatusBarNewItemAddTestingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string TemplateAdded {
            get {
                return ResourceManager.GetString("TemplateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string TemplateDetailsAuthor {
            get {
                return ResourceManager.GetString("TemplateDetailsAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies:.
        /// </summary>
        public static string TemplateDetailsDependencies {
            get {
                return ResourceManager.GetString("TemplateDetailsDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusions:.
        /// </summary>
        public static string TemplateDetailsExclusions {
            get {
                return ResourceManager.GetString("TemplateDetailsExclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frameworks:.
        /// </summary>
        public static string TemplateDetailsFrameworks {
            get {
                return ResourceManager.GetString("TemplateDetailsFrameworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is currently not available due to missing Visual Studio Workloads / Components..
        /// </summary>
        public static string TemplateDetailsInfoUnavailableDueToMissingVSWorkload {
            get {
                return ResourceManager.GetString("TemplateDetailsInfoUnavailableDueToMissingVSWorkload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout:.
        /// </summary>
        public static string TemplateDetailsLayout {
            get {
                return ResourceManager.GetString("TemplateDetailsLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (optional).
        /// </summary>
        public static string TemplateDetailsLayoutOptional {
            get {
                return ResourceManager.GetString("TemplateDetailsLayoutOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses:.
        /// </summary>
        public static string TemplateDetailsLicenses {
            get {
                return ResourceManager.GetString("TemplateDetailsLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum .NET Core Version:.
        /// </summary>
        public static string TemplateDetailsRequiredDotNetVersion {
            get {
                return ResourceManager.GetString("TemplateDetailsRequiredDotNetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Windows Sdks:.
        /// </summary>
        public static string TemplateDetailsRequiredSdks {
            get {
                return ResourceManager.GetString("TemplateDetailsRequiredSdks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Visual Studio Workloads / Components:.
        /// </summary>
        public static string TemplateDetailsRequiredVSWorkloads {
            get {
                return ResourceManager.GetString("TemplateDetailsRequiredVSWorkloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements:.
        /// </summary>
        public static string TemplateDetailsRequirements {
            get {
                return ResourceManager.GetString("TemplateDetailsRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string TemplateDetailsVersion {
            get {
                return ResourceManager.GetString("TemplateDetailsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        public static string TemplateGroup_Analytics {
            get {
                return ResourceManager.GetString("TemplateGroup_Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Launching.
        /// </summary>
        public static string TemplateGroup_ApplicationLaunching {
            get {
                return ResourceManager.GetString("TemplateGroup_ApplicationLaunching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Lifecycle.
        /// </summary>
        public static string TemplateGroup_ApplicationLifecycle {
            get {
                return ResourceManager.GetString("TemplateGroup_ApplicationLifecycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Work.
        /// </summary>
        public static string TemplateGroup_BackgroundWork {
            get {
                return ResourceManager.GetString("TemplateGroup_BackgroundWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected Experiences.
        /// </summary>
        public static string TemplateGroup_ConnectedExperiences {
            get {
                return ResourceManager.GetString("TemplateGroup_ConnectedExperiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string TemplateGroup_Data {
            get {
                return ResourceManager.GetString("TemplateGroup_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity (choose one).
        /// </summary>
        public static string TemplateGroup_Identity {
            get {
                return ResourceManager.GetString("TemplateGroup_Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging.
        /// </summary>
        public static string TemplateGroup_Packaging {
            get {
                return ResourceManager.GetString("TemplateGroup_Packaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string TemplateGroup_Tools {
            get {
                return ResourceManager.GetString("TemplateGroup_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interaction.
        /// </summary>
        public static string TemplateGroup_UserInteraction {
            get {
                return ResourceManager.GetString("TemplateGroup_UserInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the template you want to add.
        /// </summary>
        public static string TemplateSelectionTitle {
            get {
                return ResourceManager.GetString("TemplateSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By continuing, you agree to the terms of all the licenses in the licenses section..
        /// </summary>
        public static string TermsAndConditionsText {
            get {
                return ResourceManager.GetString("TermsAndConditionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UWP.
        /// </summary>
        public static string UWP {
            get {
                return ResourceManager.GetString("UWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}update-activationservice-for-identity.md.
        /// </summary>
        public static string ValidatorHasActivationServiceBeforeIdentityLink {
            get {
                return ResourceManager.GetString("ValidatorHasActivationServiceBeforeIdentityLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See documentation to update..
        /// </summary>
        public static string ValidatorHasActivationServiceBeforeIdentityLinkMessage {
            get {
                return ResourceManager.GetString("ValidatorHasActivationServiceBeforeIdentityLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Template Studio has changed the ActivationService to be able to include Identity features..
        /// </summary>
        public static string ValidatorHasActivationServiceBeforeIdentityMessage {
            get {
                return ResourceManager.GetString("ValidatorHasActivationServiceBeforeIdentityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}UWP/projectTypes/updatetonavigationview.md.
        /// </summary>
        public static string ValidatorHasHamburgerMenuLink {
            get {
                return ResourceManager.GetString("ValidatorHasHamburgerMenuLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See documentation to update..
        /// </summary>
        public static string ValidatorHasHamburgerMenuLinkMessage {
            get {
                return ResourceManager.GetString("ValidatorHasHamburgerMenuLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HamburgerMenu control is obsolete and Windows Template Studio now supports NavigationView. .
        /// </summary>
        public static string ValidatorHasHamburgerMenuMessage {
            get {
                return ResourceManager.GetString("ValidatorHasHamburgerMenuMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}updatetomultiproject.md.
        /// </summary>
        public static string ValidatorHasNoCoreProjectLink {
            get {
                return ResourceManager.GetString("ValidatorHasNoCoreProjectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See documentation to update..
        /// </summary>
        public static string ValidatorHasNoCoreProjectLinkMessage {
            get {
                return ResourceManager.GetString("ValidatorHasNoCoreProjectLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Template Studio is now adding a core project. .
        /// </summary>
        public static string ValidatorHasNoCoreProjectMessage {
            get {
                return ResourceManager.GetString("ValidatorHasNoCoreProjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}UWP/frameworks/updatemvvmlightlocator.md.
        /// </summary>
        public static string ValidatorHasOldMvvmLightLocatorLink {
            get {
                return ResourceManager.GetString("ValidatorHasOldMvvmLightLocatorLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See documentation to update..
        /// </summary>
        public static string ValidatorHasOldMvvmLightLocatorLinkMessage {
            get {
                return ResourceManager.GetString("ValidatorHasOldMvvmLightLocatorLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve changed our MVVMLight ViewModelLocator implementation to support MultiView in MVVMLight. .
        /// </summary>
        public static string ValidatorHasOldMvvmLightLocatorMessage {
            get {
                return ResourceManager.GetString("ValidatorHasOldMvvmLightLocatorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}UWP/projectTypes/updatetowinuinavigationview.md.
        /// </summary>
        public static string ValidatorHasOldNavigationViewLink {
            get {
                return ResourceManager.GetString("ValidatorHasOldNavigationViewLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See documentation to update..
        /// </summary>
        public static string ValidatorHasOldNavigationViewLinkMessage {
            get {
                return ResourceManager.GetString("ValidatorHasOldNavigationViewLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Template Studio is now using the NavigationView from Windows UI Library..
        /// </summary>
        public static string ValidatorHasOldNavigationViewMessage {
            get {
                return ResourceManager.GetString("ValidatorHasOldNavigationViewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}UWP/projectTypes/updatetohorizontalnavview.md.
        /// </summary>
        public static string ValidatorHasPivotLink {
            get {
                return ResourceManager.GetString("ValidatorHasPivotLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See documentation to update..
        /// </summary>
        public static string ValidatorHasPivotLinkMessage {
            get {
                return ResourceManager.GetString("ValidatorHasPivotLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Template Studio is now using horizontal NavigationView in Pivot projects. .
        /// </summary>
        public static string ValidatorHasPivotMessage {
            get {
                return ResourceManager.GetString("ValidatorHasPivotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Template Studio.
        /// </summary>
        public static string WindowsTemplateStudio {
            get {
                return ResourceManager.GetString("WindowsTemplateStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows UI.
        /// </summary>
        public static string WinUI {
            get {
                return ResourceManager.GetString("WinUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET desktop development.
        /// </summary>
        public static string WorkloadDisplayNameManagedDesktop {
            get {
                return ResourceManager.GetString("WorkloadDisplayNameManagedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSIX Packaging Tools.
        /// </summary>
        public static string WorkloadDisplayNameMsixPackaging {
            get {
                return ResourceManager.GetString("WorkloadDisplayNameMsixPackaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET and web development.
        /// </summary>
        public static string WorkloadDisplayNameNetWeb {
            get {
                return ResourceManager.GetString("WorkloadDisplayNameNetWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal Windows Platform development.
        /// </summary>
        public static string WorkloadDisplayNameUniversal {
            get {
                return ResourceManager.GetString("WorkloadDisplayNameUniversal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPF (.NET Core).
        /// </summary>
        public static string WPF {
            get {
                return ResourceManager.GetString("WPF", resourceCulture);
            }
        }
    }
}
