public ApplicationHostService(INavigationService navigationService, IShellPage shellPage, IThemeSelectorService themeSelectorService)
^^^-searchabove-replacebelow-vvv
public ApplicationHostService(INavigationService navigationService, IShellPage shellPage, IThemeSelectorService themeSelectorService, IPersistAndRestoreService persistAndRestoreService)