// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TemplateStudioForWinUICpp.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidTemplateStudioForWinuiPackageString = "3d84e3cf-1916-491d-a180-a2c25b9dd35c";
        public static Guid guidTemplateStudioForWinuiPackage = new Guid(guidTemplateStudioForWinuiPackageString);

        public const string guidTemplateStudioForWinuiPackageCmdSetString = "a643cab7-d87d-4872-985d-af2b5a70c30e";
        public static Guid guidTemplateStudioForWinuiPackageCmdSet = new Guid(guidTemplateStudioForWinuiPackageCmdSetString);

        public const string guidImagesString = "8ff1ed7c-a9c7-42be-b9cf-a1c039549bd7";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int AddItemContextGroup = 0x0100;
        public const int AddItemContextMenu = 0x0200;
        public const int AddItemContextMenuGroup = 0x0300;
        public const int ToolsContextMenuGroup = 0x0350;
        public const int AddPageCommand = 0x0400;
        public const int AddFeatureCommand = 0x0500;
        public const int AddServiceCommand = 0x0600;
        public const int AddTestingCommand = 0x0700;
        public const int OpenTempFolder = 0x0800;
        public const int bmpFeature1 = 0x0001;
        public const int bmpFeature2 = 0x0002;
        public const int bmpFeature3 = 0x0003;
        public const int bmpFeature4 = 0x0004;
        public const int bmpPage1 = 0x0005;
        public const int bmpWTS = 0x0006;
        public const int bmpOpenTemp = 0x0007;
        public const int bmpService = 0x0008;
        public const int bmpTesting = 0x0009;
    }
}