//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Templates.UI.V2Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Templates.UI.V2Resources.StringRes", typeof(StringRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add features.
        /// </summary>
        public static string AddFeaturesTitle {
            get {
                return ResourceManager.GetString("AddFeaturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add pages.
        /// </summary>
        public static string AddPagesTitle {
            get {
                return ResourceManager.GetString("AddPagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string ButtonRemove {
            get {
                return ResourceManager.GetString("ButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a design pattern.
        /// </summary>
        public static string FrameworkTitle {
            get {
                return ResourceManager.GetString("FrameworkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already part of your project. Please choose another feature..
        /// </summary>
        public static string NewItemHasNoChangesFeature {
            get {
                return ResourceManager.GetString("NewItemHasNoChangesFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already part of your project. Please choose another page..
        /// </summary>
        public static string NewItemHasNoChangesPage {
            get {
                return ResourceManager.GetString("NewItemHasNoChangesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template selection.
        /// </summary>
        public static string NewItemStepOne {
            get {
                return ResourceManager.GetString("NewItemStepOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes summary.
        /// </summary>
        public static string NewItemStepTwo {
            get {
                return ResourceManager.GetString("NewItemStepTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string NewItemTemplateDetailsDependenciesSectionTitle {
            get {
                return ResourceManager.GetString("NewItemTemplateDetailsDependenciesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string NewItemTemplateDetailsLicensesSectionTitle {
            get {
                return ResourceManager.GetString("NewItemTemplateDetailsLicensesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NewItemTemplateDetailsNameSectionTitle {
            get {
                return ResourceManager.GetString("NewItemTemplateDetailsNameSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Details.
        /// </summary>
        public static string NewItemTemplateDetailsTitle {
            get {
                return ResourceManager.GetString("NewItemTemplateDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New feature.
        /// </summary>
        public static string NewItemTitleFeature {
            get {
                return ResourceManager.GetString("NewItemTitleFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New page.
        /// </summary>
        public static string NewItemTitlePage {
            get {
                return ResourceManager.GetString("NewItemTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string NewProjectStepFour {
            get {
                return ResourceManager.GetString("NewProjectStepFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project type.
        /// </summary>
        public static string NewProjectStepOne {
            get {
                return ResourceManager.GetString("NewProjectStepOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string NewProjectStepThree {
            get {
                return ResourceManager.GetString("NewProjectStepThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design pattern.
        /// </summary>
        public static string NewProjectStepTwo {
            get {
                return ResourceManager.GetString("NewProjectStepTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Universal Windows Platform app.
        /// </summary>
        public static string NewProjectTitle {
            get {
                return ResourceManager.GetString("NewProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not remove {0} because {1} depends on it..
        /// </summary>
        public static string NotificationRemoveError_Dependency {
            get {
                return ResourceManager.GetString("NotificationRemoveError_Dependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed..
        /// </summary>
        public static string NotificationSyncStatus_Acquired {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_Acquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are new templates available (v{0}). Downloading….
        /// </summary>
        public static string NotificationSyncStatus_Acquiring {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_Acquiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        public static string NotificationSyncStatus_CheckedForUpdates {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_CheckedForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for template updates....
        /// </summary>
        public static string NotificationSyncStatus_CheckingForUpdates {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Template Studio Version {0} is available. Update the extension to enjoy the latest features..
        /// </summary>
        public static string NotificationSyncStatus_NewWizardVersionAvailable {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_NewWizardVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates ready..
        /// </summary>
        public static string NotificationSyncStatus_Prepared {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_Prepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing templates (v{0})....
        /// </summary>
        public static string NotificationSyncStatus_Preparing {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates updated..
        /// </summary>
        public static string NotificationSyncStatus_Updated {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing templates cache….
        /// </summary>
        public static string NotificationSyncStatus_Updating {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already exists.
        /// </summary>
        public static string NotificationValidationError_AlreadyExists {
            get {
                return ResourceManager.GetString("NotificationValidationError_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only alphanumeric and &apos;_&apos; characters are allowed.
        /// </summary>
        public static string NotificationValidationError_BadFormat {
            get {
                return ResourceManager.GetString("NotificationValidationError_BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty.
        /// </summary>
        public static string NotificationValidationError_Empty {
            get {
                return ResourceManager.GetString("NotificationValidationError_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is reserved.
        /// </summary>
        public static string NotificationValidationError_ReservedName {
            get {
                return ResourceManager.GetString("NotificationValidationError_ReservedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string ProjectDetailsFeaturesSectionTitle {
            get {
                return ResourceManager.GetString("ProjectDetailsFeaturesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design pattern.
        /// </summary>
        public static string ProjectDetailsFrameworkSectionTitle {
            get {
                return ResourceManager.GetString("ProjectDetailsFrameworkSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string ProjectDetailsLicensesSectionTitle {
            get {
                return ResourceManager.GetString("ProjectDetailsLicensesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string ProjectDetailsPagesSectionTitle {
            get {
                return ResourceManager.GetString("ProjectDetailsPagesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project type.
        /// </summary>
        public static string ProjectDetailsProjectTypeSectionTitle {
            get {
                return ResourceManager.GetString("ProjectDetailsProjectTypeSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your project details.
        /// </summary>
        public static string ProjectDetailsTitle {
            get {
                return ResourceManager.GetString("ProjectDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a project type.
        /// </summary>
        public static string ProjectTypeTitle {
            get {
                return ResourceManager.GetString("ProjectTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string TemplateDetailsAuthor {
            get {
                return ResourceManager.GetString("TemplateDetailsAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies:.
        /// </summary>
        public static string TemplateDetailsDependencies {
            get {
                return ResourceManager.GetString("TemplateDetailsDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses:.
        /// </summary>
        public static string TemplateDetailsLicenses {
            get {
                return ResourceManager.GetString("TemplateDetailsLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string TemplateDetailsVersion {
            get {
                return ResourceManager.GetString("TemplateDetailsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the template you want to add.
        /// </summary>
        public static string TemplateSelectionTitle {
            get {
                return ResourceManager.GetString("TemplateSelectionTitle", resourceCulture);
            }
        }
    }
}
