//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Templates.UI.V2Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Templates.UI.V2Resources.StringRes", typeof(StringRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add features.
        /// </summary>
        public static string AddFeaturesTitle {
            get {
                return ResourceManager.GetString("AddFeaturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add pages.
        /// </summary>
        public static string AddPagesTitle {
            get {
                return ResourceManager.GetString("AddPagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a design pattern.
        /// </summary>
        public static string FrameworkTitle {
            get {
                return ResourceManager.GetString("FrameworkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Universal Windows Platform app.
        /// </summary>
        public static string NewProjectTitle {
            get {
                return ResourceManager.GetString("NewProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        public static string NotificationSyncStatus_Acquired {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_Acquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for template updates....
        /// </summary>
        public static string NotificationSyncStatus_Acquiring {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_Acquiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is new template content available..
        /// </summary>
        public static string NotificationSyncStatus_NewVersionAvailable {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update to the templates is available but not compatible with this wizard version. Update the extension to access the latest templates..
        /// </summary>
        public static string NotificationSyncStatus_OverVersion {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_OverVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no content available for this extension version. Update the extension to access to the latest content..
        /// </summary>
        public static string NotificationSyncStatus_OverVersionNoContent {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_OverVersionNoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates ready..
        /// </summary>
        public static string NotificationSyncStatus_Prepared {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_Prepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing templates for first use....
        /// </summary>
        public static string NotificationSyncStatus_Preparing {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates updated..
        /// </summary>
        public static string NotificationSyncStatus_Updated {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating templates....
        /// </summary>
        public static string NotificationSyncStatus_Updating {
            get {
                return ResourceManager.GetString("NotificationSyncStatus_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string ProjectDetailsFeaturesSectionTitle {
            get {
                return ResourceManager.GetString("ProjectDetailsFeaturesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design pattern.
        /// </summary>
        public static string ProjectDetailsFrameworkSectionTitle {
            get {
                return ResourceManager.GetString("ProjectDetailsFrameworkSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string ProjectDetailsPagesSectionTitle {
            get {
                return ResourceManager.GetString("ProjectDetailsPagesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project type.
        /// </summary>
        public static string ProjectDetailsProjectTypeSectionTitle {
            get {
                return ResourceManager.GetString("ProjectDetailsProjectTypeSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your project details.
        /// </summary>
        public static string ProjectDetailsTitle {
            get {
                return ResourceManager.GetString("ProjectDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a project type.
        /// </summary>
        public static string ProjectTypeTitle {
            get {
                return ResourceManager.GetString("ProjectTypeTitle", resourceCulture);
            }
        }
    }
}
