// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TemplateStudioForWPF
{
    internal sealed partial class Vsix
    {
        public const string Id = "TemplateStudioForWPF.f4e060e0-bdf6-4ed0-9924-983506ec9862";
        public const string Name = "Template Studio for WPF";
        public const string Description = @"Template Studio accelerates the creation of new WPF apps using a wizard-based UI.";
        public const string Language = "en-US";
        public const string Version = "5.0";
        public const string Author = "Microsoft";
        public const string Tags = "Template Studio, WPF, XAML, MVVM, Desktop";
    }
}
