        Private Sub RefreshCommands()
            '{[{
            Dim copy = TryCast(CopyCommand, RelayCommand)
            copy?.OnCanExecuteChanged()
            Dim cut = TryCast(CutCommand, RelayCommand)
            cut?.OnCanExecuteChanged()
            Dim paste = TryCast(PasteCommand, RelayCommand)
            paste?.OnCanExecuteChanged()
            Dim undo = TryCast(UndoCommand, RelayCommand)
            undo?.OnCanExecuteChanged()
            Dim redo = TryCast(RedoCommand, RelayCommand)
            redo?.OnCanExecuteChanged()
            Dim saveInk = TryCast(SaveInkFileCommand, RelayCommand)
            saveInk?.OnCanExecuteChanged()
            Dim export = TryCast(ExportAsImageCommand, RelayCommand)
            export?.OnCanExecuteChanged()
            Dim clearAll = TryCast(ClearAllCommand, RelayCommand)
            clearAll?.OnCanExecuteChanged()
            '}]}
        End Sub
