//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Templates.Wizard.PostActions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PostActionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PostActionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Templates.Wizard.PostActions.PostActionResources", typeof(PostActionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postaction AddItemToProject: Error adding items to project..
        /// </summary>
        internal static string AddItemToProject_Error {
            get {
                return ResourceManager.GetString("AddItemToProject_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postaction AddItemToProject: Successfully added items to project..
        /// </summary>
        internal static string AddItemToProject_Success {
            get {
                return ResourceManager.GetString("AddItemToProject_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postaction AddProjectToSolution: Error adding projects to solution..
        /// </summary>
        internal static string AddProjectToSolution_Error {
            get {
                return ResourceManager.GetString("AddProjectToSolution_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postaction AddProjectToSolution: Successfully added projects to solution..
        /// </summary>
        internal static string AddProjectToSolution_Success {
            get {
                return ResourceManager.GetString("AddProjectToSolution_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation parameter UserName should not be empty..
        /// </summary>
        internal static string GenerateTestCertificate_EmptyUserName {
            get {
                return ResourceManager.GetString("GenerateTestCertificate_EmptyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postaction GenerateTestCertificate: Error in certificate generation..
        /// </summary>
        internal static string GenerateTestCertificate_Error {
            get {
                return ResourceManager.GetString("GenerateTestCertificate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postaction GenerateTestCertificate: Certificate generated successfully..
        /// </summary>
        internal static string GenerateTestCertificate_Success {
            get {
                return ResourceManager.GetString("GenerateTestCertificate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postaction InsertPartialGeneration {0}: Could not insert code {1} on anchor {2} in file {3}. Please copy the code and insert it manually..
        /// </summary>
        internal static string InsertPartialGeneration_AnchorNotFoundPattern {
            get {
                return ResourceManager.GetString("InsertPartialGeneration_AnchorNotFoundPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postaction InsertPartialGeneration {0}: Parameter destination.anchor should not be empty.
        /// </summary>
        internal static string InsertPartialGeneration_EmptyDestinationAnchorPattern {
            get {
                return ResourceManager.GetString("InsertPartialGeneration_EmptyDestinationAnchorPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postaction InsertPartialGeneration {0}: Parameter destination.filename should not be empty.
        /// </summary>
        internal static string InsertPartialGeneration_EmptyDestinationFileNamePattern {
            get {
                return ResourceManager.GetString("InsertPartialGeneration_EmptyDestinationFileNamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postaction InsertPartialGeneration {0}: Error inserting partial generation..
        /// </summary>
        internal static string InsertPartialGeneration_ErrorPattern {
            get {
                return ResourceManager.GetString("InsertPartialGeneration_ErrorPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} was not found..
        /// </summary>
        internal static string InsertPartialGeneration_FileNotFoundPattern {
            get {
                return ResourceManager.GetString("InsertPartialGeneration_FileNotFoundPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postaction InsertPartialGeneration {0}: Successfully inserted code {1} on anchor {2} in file {3}.
        /// </summary>
        internal static string InsertPartialGeneration_SuccessPattern {
            get {
                return ResourceManager.GetString("InsertPartialGeneration_SuccessPattern", resourceCulture);
            }
        }
    }
}
