        Private Sub RefreshCommands()
            '{[{
            Dim copy = TryCast(CopyCommand, RelayCommand)
            copy?.RaiseCanExecuteChanged()
            Dim cut = TryCast(CutCommand, RelayCommand)
            cut?.RaiseCanExecuteChanged()
            Dim paste = TryCast(PasteCommand, RelayCommand)
            paste?.RaiseCanExecuteChanged()
            Dim undo = TryCast(UndoCommand, RelayCommand)
            undo?.RaiseCanExecuteChanged()
            Dim redo = TryCast(RedoCommand, RelayCommand)
            redo?.RaiseCanExecuteChanged()
            Dim saveInk = TryCast(SaveInkFileCommand, RelayCommand)
            saveInk?.RaiseCanExecuteChanged()
            Dim export = TryCast(ExportAsImageCommand, RelayCommand)
            export?.RaiseCanExecuteChanged()
            Dim clearAll = TryCast(ClearAllCommand, RelayCommand)
            clearAll?.RaiseCanExecuteChanged()
            '}]}
        End Sub