//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Templates.Wizard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Templates.Wizard.Resources.StringRes", typeof(StringRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Feature.
        /// </summary>
        public static string AddFeatureAction {
            get {
                return ResourceManager.GetString("AddFeatureAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Page.
        /// </summary>
        public static string AddPageAction {
            get {
                return ResourceManager.GetString("AddPageAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding &apos;{0}&apos; page to project....
        /// </summary>
        public static string AddPageMessage {
            get {
                return ResourceManager.GetString("AddPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Project.
        /// </summary>
        public static string AddProjectAction {
            get {
                return ResourceManager.GetString("AddProjectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating project &apos;{0}&apos;....
        /// </summary>
        public static string AddProjectMessage {
            get {
                return ResourceManager.GetString("AddProjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating templates. See output for more details..
        /// </summary>
        public static string ErrorSync {
            get {
                return ResourceManager.GetString("ErrorSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template &apos;{0}&apos;, name: &apos;{1}&apos;, reason: &apos;{2}&apos;.
        /// </summary>
        public static string ExceptionGenerating {
            get {
                return ResourceManager.GetString("ExceptionGenerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error generating the project: {0}.
        /// </summary>
        public static string ExceptionUnexpectedGenerating {
            get {
                return ResourceManager.GetString("ExceptionUnexpectedGenerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error in template selector wizard: {0}.
        /// </summary>
        public static string ExceptionUnexpectedWizard {
            get {
                return ResourceManager.GetString("ExceptionUnexpectedWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restauring packages....
        /// </summary>
        public static string RestauringMessage {
            get {
                return ResourceManager.GetString("RestauringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates downloaded.
        /// </summary>
        public static string StatusAdquired {
            get {
                return ResourceManager.GetString("StatusAdquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading templates....
        /// </summary>
        public static string StatusAdquiring {
            get {
                return ResourceManager.GetString("StatusAdquiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates updated.
        /// </summary>
        public static string StatusUpdated {
            get {
                return ResourceManager.GetString("StatusUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating templates....
        /// </summary>
        public static string StatusUpdating {
            get {
                return ResourceManager.GetString("StatusUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action cancelled by user..
        /// </summary>
        public static string UIActionCancelled {
            get {
                return ResourceManager.GetString("UIActionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding page....
        /// </summary>
        public static string UIAddPage {
            get {
                return ResourceManager.GetString("UIAddPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding project....
        /// </summary>
        public static string UIAddProjectAdding {
            get {
                return ResourceManager.GetString("UIAddProjectAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating your project....
        /// </summary>
        public static string UIAddProjectGenerating {
            get {
                return ResourceManager.GetString("UIAddProjectGenerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. The feature can&apos;t be generated..
        /// </summary>
        public static string UIErrorFeatureCantBeAdded {
            get {
                return ResourceManager.GetString("UIErrorFeatureCantBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. The the page can&apos;t be generated..
        /// </summary>
        public static string UIErrorPageCantBeAdded {
            get {
                return ResourceManager.GetString("UIErrorPageCantBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. The project can&apos;t be generated..
        /// </summary>
        public static string UIErrorProjectCantBeGenerated {
            get {
                return ResourceManager.GetString("UIErrorProjectCantBeGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UWP Community Templates: {0}.
        /// </summary>
        public static string UIMessageBoxTitlePattern {
            get {
                return ResourceManager.GetString("UIMessageBoxTitlePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before adding a page you must select a project in the Solution Explorer..
        /// </summary>
        public static string UINoActiveProjectMessage {
            get {
                return ResourceManager.GetString("UINoActiveProjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page &apos;{0}&apos; successfully added..
        /// </summary>
        public static string UIPageAddedPattern {
            get {
                return ResourceManager.GetString("UIPageAddedPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project successfully created..
        /// </summary>
        public static string UIProjectSuccessfullyCreated {
            get {
                return ResourceManager.GetString("UIProjectSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Exception.\n{0}.
        /// </summary>
        public static string UnexpectedExPattern {
            get {
                return ResourceManager.GetString("UnexpectedExPattern", resourceCulture);
            }
        }
    }
}
