//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Templates.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Templates.Core.Resources.StringRes", typeof(StringRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Additional Message.
        /// </summary>
        internal static string AdditionalMessageString {
            get {
                return ResourceManager.GetString("AdditionalMessageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Addtional Exception Info.
        /// </summary>
        internal static string AddtionalExceptionInfoString {
            get {
                return ResourceManager.GetString("AddtionalExceptionInfoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assembly File Version.
        /// </summary>
        internal static string AssemblyFileVersionString {
            get {
                return ResourceManager.GetString("AssemblyFileVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The query &quot;{0}&quot; is not valid. Allowed operators are &apos;==&apos; or &apos;!=&apos;. Multiple conditions are separated by &apos;&amp;&apos;..
        /// </summary>
        internal static string CompositionQueryParseMessage {
            get {
                return ResourceManager.GetString("CompositionQueryParseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration file loaded.
        /// </summary>
        internal static string ConfigurationFileLoadedString {
            get {
                return ResourceManager.GetString("ConfigurationFileLoadedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current content expiration.
        /// </summary>
        internal static string CurrentContentExpirationString {
            get {
                return ResourceManager.GetString("CurrentContentExpirationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exception Info.
        /// </summary>
        internal static string ExceptionInfoString {
            get {
                return ResourceManager.GetString("ExceptionInfoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exception.
        /// </summary>
        internal static string ExceptionString {
            get {
                return ResourceManager.GetString("ExceptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exception Tracked.
        /// </summary>
        internal static string ExceptionTrackedString {
            get {
                return ResourceManager.GetString("ExceptionTrackedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not find file &apos;{0}&apos; to include the following changes. Please review the code blocks to include the changes manually where required in your project. Related Template: &apos;{1}&apos;..
        /// </summary>
        internal static string FailedMergePostActionFileNotFound {
            get {
                return ResourceManager.GetString("FailedMergePostActionFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The style with key &apos;{0}&apos; is already defined with different value or elements in this file. Please review the styles to include the changes manually where required in your project. Related Template: &apos;{1}&apos;..
        /// </summary>
        internal static string FailedMergePostActionKeyAlreadyDefined {
            get {
                return ResourceManager.GetString("FailedMergePostActionKeyAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not find the expected line `{0}` in file &apos;{1}&apos;. Please merge the content from the postaction file manually. Related Template: &apos;{2}&apos;..
        /// </summary>
        internal static string FailedMergePostActionLineNotFound {
            get {
                return ResourceManager.GetString("FailedMergePostActionLineNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The folder {0} can&apos;t be copied to {1}. Error: {2}.
        /// </summary>
        internal static string FsSafeCopyFileMessage {
            get {
                return ResourceManager.GetString("FsSafeCopyFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The folder {0} can&apos;t be delete. Error: {1}.
        /// </summary>
        internal static string FsSafeDeleteDirectoryMessage {
            get {
                return ResourceManager.GetString("FsSafeDeleteDirectoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The file {0} can&apos;t be delete. Error: {1}.
        /// </summary>
        internal static string FsSafeDeleteFileMessage {
            get {
                return ResourceManager.GetString("FsSafeDeleteFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The folder {0} can&apos;t be moved to {1}. Error: {2}.
        /// </summary>
        internal static string FsSafeMoveDirectoryMessage {
            get {
                return ResourceManager.GetString("FsSafeMoveDirectoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Critical error initializating GenContext..
        /// </summary>
        internal static string GenContextBootstrapError {
            get {
                return ResourceManager.GetString("GenContextBootstrapError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is no context for the current gen execution, call Current_set first.
        /// </summary>
        internal static string GenContextCurrentInvalidOperationMessage {
            get {
                return ResourceManager.GetString("GenContextCurrentInvalidOperationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error generating certificate..
        /// </summary>
        internal static string GenerateTestCertificatePostActionExecute {
            get {
                return ResourceManager.GetString("GenerateTestCertificatePostActionExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log started.
        /// </summary>
        internal static string LogStartedString {
            get {
                return ResourceManager.GetString("LogStartedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Recommended Markdown viewer: [Markdown Editor VS Extension](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.MarkdownEditor)*.
        /// </summary>
        internal static string MarkdownHeader {
            get {
                return ResourceManager.GetString("MarkdownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is no merge target for file &apos;{0}&apos;. Related Template: &apos;{1}&apos;..
        /// </summary>
        internal static string MergeFileNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("MergeFileNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Line {0} not found in file &apos;{1}&apos;. Related Template: &apos;{2}&apos;..
        /// </summary>
        internal static string MergeLineNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("MergeLineNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is no merge target for file &apos;{0}&apos;.
        /// </summary>
        internal static string MergePostActionExecuteMessage {
            get {
                return ResourceManager.GetString("MergePostActionExecuteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to infer a name. Too many iterations.
        /// </summary>
        internal static string NamingInferMessage {
            get {
                return ResourceManager.GetString("NamingInferMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package certificate.
        /// </summary>
        internal static string PackageCertificateString {
            get {
                return ResourceManager.GetString("PackageCertificateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error executing &apos;{0}&apos;. Ignoring the error as Continue on Error is enabled. Related template: {1}..
        /// </summary>
        internal static string PostActionContinuerOnErrorWarning {
            get {
                return ResourceManager.GetString("PostActionContinuerOnErrorWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error executing &apos;{0}&apos;. Related template: {1}..
        /// </summary>
        internal static string PostActionException {
            get {
                return ResourceManager.GetString("PostActionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The PostAction.ActionId &apos;{0}&apos; defined in the template does not match with the expected class ActionId &apos;{1}&apos;. Can&apos;t continue. Related template: {2}..
        /// </summary>
        internal static string PostActionIdsNotMatchError {
            get {
                return ResourceManager.GetString("PostActionIdsNotMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a None.
        /// </summary>
        internal static string PostActionRelatedNone {
            get {
                return ResourceManager.GetString("PostActionRelatedNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error downloading from {0}. Internet connection is required to download template updates..
        /// </summary>
        internal static string RemoteTemplatesSourceDownloadContentKoErrorMessage {
            get {
                return ResourceManager.GetString("RemoteTemplatesSourceDownloadContentKoErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Templates content can&apos;t be downloaded right now, we will try it later..
        /// </summary>
        internal static string RemoteTemplatesSourceDownloadContentKoInfoMessage {
            get {
                return ResourceManager.GetString("RemoteTemplatesSourceDownloadContentKoInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Templates content downloaded to {0} from {1}..
        /// </summary>
        internal static string RemoteTemplatesSourceDownloadContentOkMessage {
            get {
                return ResourceManager.GetString("RemoteTemplatesSourceDownloadContentOkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error syncing templates. Status:.
        /// </summary>
        internal static string RepositorySynchronizationExceptionMessage {
            get {
                return ResourceManager.GetString("RepositorySynchronizationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adding items to project ....
        /// </summary>
        internal static string StatusAddingItems {
            get {
                return ResourceManager.GetString("StatusAddingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opening generated files ....
        /// </summary>
        internal static string StatusOpeningItems {
            get {
                return ResourceManager.GetString("StatusOpeningItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steps to include new item generation.md.
        /// </summary>
        internal static string SyncInstructionsFileName {
            get {
                return ResourceManager.GetString("SyncInstructionsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ## Conflicting files:
        ///These files already exist in your project and were also generated as part of the new item.
        ///Please compare and make sure everything is in the right place:
        ///{0}.
        /// </summary>
        internal static string SyncInstructionsSectionConflictingFiles {
            get {
                return ResourceManager.GetString("SyncInstructionsSectionConflictingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ## Modified files:
        ///To integrate your new item with the existing project apply the following changes:
        ///{0}.
        /// </summary>
        internal static string SyncInstructionsSectionModifiedFiles {
            get {
                return ResourceManager.GetString("SyncInstructionsSectionModifiedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ## New files:
        ///Copy and add the following files to your project:
        ///{0}.
        /// </summary>
        internal static string SyncInstructionsSectionNewFiles {
            get {
                return ResourceManager.GetString("SyncInstructionsSectionNewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ## Unchanged files:
        ///These files already exist in your project, no action is necessary:
        ///{0}.
        /// </summary>
        internal static string SyncInstructionsSectionUnchangedFiles {
            get {
                return ResourceManager.GetString("SyncInstructionsSectionUnchangedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Recommended Markdown viewer: [Markdown Editor VS Extension](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.MarkdownEditor)*
        ///
        ///# Steps to include new item generation
        ///Please follow the instructions to include the new item into you project:
        ///
        ///You can find all referenced files in the temporary generation folder: {0}
        ///
        ///{1}
        ///{2}
        ///{3}
        ///{4}.
        /// </summary>
        internal static string SyncInstructionsTemplate {
            get {
                return ResourceManager.GetString("SyncInstructionsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 
        ///### Changes required in file &apos;{0}&apos;:
        ///{1}
        ///Preview the changes in: {2}.
        /// </summary>
        internal static string SyncInstructionsTemplateModifiedFile {
            get {
                return ResourceManager.GetString("SyncInstructionsTemplateModifiedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GenerationSummary.md.
        /// </summary>
        internal static string SyncSummaryFileName {
            get {
                return ResourceManager.GetString("SyncSummaryFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ProjectFile.
        /// </summary>
        internal static string SyncSummaryProjectFile {
            get {
                return ResourceManager.GetString("SyncSummaryProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ## Conflicting files:
        ///These files already exist in your project and were also generated as part of the new item.
        ///Please compare and make sure everything is in the right place.
        ///{0}.
        /// </summary>
        internal static string SyncSummarySectionConflictingFiles {
            get {
                return ResourceManager.GetString("SyncSummarySectionConflictingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ## Failed changes in files:
        ///Merges in the following files failed:
        ///{0}.
        /// </summary>
        internal static string SyncSummarySectionFailedMergeFiles {
            get {
                return ResourceManager.GetString("SyncSummarySectionFailedMergeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ## Modified files:
        ///The following changes have been applied:
        ///{0}.
        /// </summary>
        internal static string SyncSummarySectionModifiedFiles {
            get {
                return ResourceManager.GetString("SyncSummarySectionModifiedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ## New files:
        ///These files have been added to your project.
        ///{0}.
        /// </summary>
        internal static string SyncSummarySectionNewFiles {
            get {
                return ResourceManager.GetString("SyncSummarySectionNewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temp.
        /// </summary>
        internal static string SyncSummaryTempGenerationFile {
            get {
                return ResourceManager.GetString("SyncSummaryTempGenerationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Recommended Markdown viewer: [Markdown Editor VS Extension](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.MarkdownEditor)*
        ///
        ///# Generation summary
        ///The following changes have been incorporated into your project:
        ///
        ///You can find the files from the generation in the temporary generation folder: {0}
        ///
        ///{1}
        ///{2}
        ///{3}
        ///{4}.
        /// </summary>
        internal static string SyncSummaryTemplate {
            get {
                return ResourceManager.GetString("SyncSummaryTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 
        ///### Changes in file &apos;{0}&apos;:
        ///The following changes could not be integrated: {2}
        ///{1}.
        /// </summary>
        internal static string SyncSummaryTemplateFailedMerges {
            get {
                return ResourceManager.GetString("SyncSummaryTemplateFailedMerges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 
        ///### Changes in file &apos;{0}&apos;:
        ///See the final result: {2}
        ///
        ///{1}.
        /// </summary>
        internal static string SyncSummaryTemplateModifiedFile {
            get {
                return ResourceManager.GetString("SyncSummaryTemplateModifiedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid digital signatures in &apos;{0}&apos;. The content has been tampered or the certificate is not present, not valid or not allowed.  Unable to continue..
        /// </summary>
        internal static string TemplatePackageExtractMessage {
            get {
                return ResourceManager.GetString("TemplatePackageExtractMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Found {0} certificates matching the thumbprint {1} in the store {2}.
        /// </summary>
        internal static string TemplatePackageFindCertificateFoundMessage {
            get {
                return ResourceManager.GetString("TemplatePackageFindCertificateFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The certificate found does not have private key..
        /// </summary>
        internal static string TemplatePackageFindCertificateNoPkMessage {
            get {
                return ResourceManager.GetString("TemplatePackageFindCertificateNoPkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a More than one certificate found matching the thumbrint. Returning the first one..
        /// </summary>
        internal static string TemplatePackageFindCertificateNotOneMessage {
            get {
                return ResourceManager.GetString("TemplatePackageFindCertificateNotOneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The specified source &apos;{0}&apos; is invalid, the file does not exist, or the folder is empty..
        /// </summary>
        internal static string TemplatePackageGetSourceFilesMessage {
            get {
                return ResourceManager.GetString("TemplatePackageGetSourceFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No certificate found matching the thumbrint {0}. Searched on CurrentUser/My and LocalMachine/My stores..
        /// </summary>
        internal static string TemplatePackageLoadCertMessage {
            get {
                return ResourceManager.GetString("TemplatePackageLoadCertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The certificate with thumbprint {0} can&apos;t be found in CurrentUser/My or LocalMachine/My..
        /// </summary>
        internal static string TemplatePackagePackAndSignMessage {
            get {
                return ResourceManager.GetString("TemplatePackagePackAndSignMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error signing package..
        /// </summary>
        internal static string TemplatePackageSignAllPartsMessage {
            get {
                return ResourceManager.GetString("TemplatePackageSignAllPartsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package signature certificate validation not passed..
        /// </summary>
        internal static string TemplatePackageValidatePackageCertificatesMessage {
            get {
                return ResourceManager.GetString("TemplatePackageValidatePackageCertificatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificate &apos;{0}&apos; verification finished with status &apos;{1}&apos;.
        /// </summary>
        internal static string TemplatePackageVerifyCertificateMessage {
            get {
                return ResourceManager.GetString("TemplatePackageVerifyCertificateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Templates extracted to.
        /// </summary>
        internal static string TemplatesContentExtractedToString {
            get {
                return ResourceManager.GetString("TemplatesContentExtractedToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The templates can&apos;t be extracted..
        /// </summary>
        internal static string TemplatesSourceExtractContentMessage {
            get {
                return ResourceManager.GetString("TemplatesSourceExtractContentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to purge old content..
        /// </summary>
        internal static string TemplatesSynchronizationPurgeContentAsyncMessage {
            get {
                return ResourceManager.GetString("TemplatesSynchronizationPurgeContentAsyncMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other instance is syncing templates... Waiting 5 seconds..
        /// </summary>
        internal static string TemplatesSynchronizationWaitingOtherInstanceMessage {
            get {
                return ResourceManager.GetString("TemplatesSynchronizationWaitingOtherInstanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error creating the instance locking file..
        /// </summary>
        internal static string TemplatesSynchronizationWarnCreatingLockFileMessage {
            get {
                return ResourceManager.GetString("TemplatesSynchronizationWarnCreatingLockFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error deleting the instance locking file..
        /// </summary>
        internal static string TemplatesSynchronizationWarnDeletingLockFileMessage {
            get {
                return ResourceManager.GetString("TemplatesSynchronizationWarnDeletingLockFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error reading the instance locking file..
        /// </summary>
        internal static string TemplatesSynchronizationWarnReadingLockFileMessage {
            get {
                return ResourceManager.GetString("TemplatesSynchronizationWarnReadingLockFileMessage", resourceCulture);
            }
        }
    }
}
