//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Templates.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Templates.Core.Resources.StringRes", typeof(StringRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Message.
        /// </summary>
        internal static string AdditionalMessageString {
            get {
                return ResourceManager.GetString("AdditionalMessageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addtional Exception Info.
        /// </summary>
        internal static string AddtionalExceptionInfoString {
            get {
                return ResourceManager.GetString("AddtionalExceptionInfoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly File Version.
        /// </summary>
        internal static string AssemblyFileVersionString {
            get {
                return ResourceManager.GetString("AssemblyFileVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query &quot;{0}&quot; is not valid. Allowed operators are &apos;==&apos; or &apos;!=&apos;. Multiple conditions are separated by &apos;&amp;&apos;..
        /// </summary>
        internal static string CompositionQueryParseMessage {
            get {
                return ResourceManager.GetString("CompositionQueryParseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file loaded.
        /// </summary>
        internal static string ConfigurationFileLoadedString {
            get {
                return ResourceManager.GetString("ConfigurationFileLoadedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current content expiration.
        /// </summary>
        internal static string CurrentContentExpirationString {
            get {
                return ResourceManager.GetString("CurrentContentExpirationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Info.
        /// </summary>
        internal static string ExceptionInfoString {
            get {
                return ResourceManager.GetString("ExceptionInfoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string ExceptionString {
            get {
                return ResourceManager.GetString("ExceptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Tracked.
        /// </summary>
        internal static string ExceptionTrackedString {
            get {
                return ResourceManager.GetString("ExceptionTrackedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file &apos;{0}&apos; to include the following changes. Please review the code blocks to include the changes manually where required in your project. .
        /// </summary>
        internal static string FailedMergePostActionFileNotFound {
            get {
                return ResourceManager.GetString("FailedMergePostActionFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the expected line `{0}` in file &apos;{1}&apos;. Please merge the content from the postaction file manually..
        /// </summary>
        internal static string FailedMergePostActionLineNotFound {
            get {
                return ResourceManager.GetString("FailedMergePostActionLineNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder {0} can&apos;t be copied to {1}. Error: {2}.
        /// </summary>
        internal static string FsSafeCopyFileMessage {
            get {
                return ResourceManager.GetString("FsSafeCopyFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder {0} can&apos;t be delete. Error: {1}.
        /// </summary>
        internal static string FsSafeDeleteDirectoryMessage {
            get {
                return ResourceManager.GetString("FsSafeDeleteDirectoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} can&apos;t be delete. Error: {1}.
        /// </summary>
        internal static string FsSafeDeleteFileMessage {
            get {
                return ResourceManager.GetString("FsSafeDeleteFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder {0} can&apos;t be moved to {1}. Error: {2}.
        /// </summary>
        internal static string FsSafeMoveDirectoryMessage {
            get {
                return ResourceManager.GetString("FsSafeMoveDirectoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error initializating GenContext..
        /// </summary>
        internal static string GenContextBootstrapError {
            get {
                return ResourceManager.GetString("GenContextBootstrapError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no context for the current gen execution, call Current_set first.
        /// </summary>
        internal static string GenContextCurrentInvalidOperationMessage {
            get {
                return ResourceManager.GetString("GenContextCurrentInvalidOperationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating certificate..
        /// </summary>
        internal static string GenerateTestCertificatePostActionExecute {
            get {
                return ResourceManager.GetString("GenerateTestCertificatePostActionExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log started.
        /// </summary>
        internal static string LogStartedString {
            get {
                return ResourceManager.GetString("LogStartedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Recommended Markdown viewer: [Markdown Editor VS Extension](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.MarkdownEditor)*.
        /// </summary>
        internal static string MarkdownHeader {
            get {
                return ResourceManager.GetString("MarkdownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no merge target for file &apos;{0}&apos;.
        /// </summary>
        internal static string MergeFileNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("MergeFileNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0} not found in file &apos;{1}&apos;.
        /// </summary>
        internal static string MergeLineNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("MergeLineNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no merge target for file &apos;{0}&apos;.
        /// </summary>
        internal static string MergePostActionExecuteMessage {
            get {
                return ResourceManager.GetString("MergePostActionExecuteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to infer a name. Too many iterations.
        /// </summary>
        internal static string NamingInferMessage {
            get {
                return ResourceManager.GetString("NamingInferMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package certificate.
        /// </summary>
        internal static string PackageCertificateString {
            get {
                return ResourceManager.GetString("PackageCertificateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading from {0}. Internet connection is required to download template updates..
        /// </summary>
        internal static string RemoteTemplatesSourceDownloadContentKoErrorMessage {
            get {
                return ResourceManager.GetString("RemoteTemplatesSourceDownloadContentKoErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates content can&apos;t be downloaded right now, we will try it later..
        /// </summary>
        internal static string RemoteTemplatesSourceDownloadContentKoInfoMessage {
            get {
                return ResourceManager.GetString("RemoteTemplatesSourceDownloadContentKoInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates content downloaded to {0} from {1}..
        /// </summary>
        internal static string RemoteTemplatesSourceDownloadContentOkMessage {
            get {
                return ResourceManager.GetString("RemoteTemplatesSourceDownloadContentOkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error syncing templates. Status:.
        /// </summary>
        internal static string RepositorySynchronizationExceptionMessage {
            get {
                return ResourceManager.GetString("RepositorySynchronizationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding items to project ....
        /// </summary>
        internal static string StatusAddingItems {
            get {
                return ResourceManager.GetString("StatusAddingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening generated files ....
        /// </summary>
        internal static string StatusOpeningItems {
            get {
                return ResourceManager.GetString("StatusOpeningItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Conflicting files:.
        /// </summary>
        internal static string SyncInstructionsConflictingFiles {
            get {
                return ResourceManager.GetString("SyncInstructionsConflictingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These files already exist in your project and were also generated as part of the new item.
        ///Please compare and make sure everything is in the right place..
        /// </summary>
        internal static string SyncInstructionsConflictingFilesDescription {
            get {
                return ResourceManager.GetString("SyncInstructionsConflictingFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please follow the indications to include the new item into you project:.
        /// </summary>
        internal static string SyncInstructionsDescription {
            get {
                return ResourceManager.GetString("SyncInstructionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps to include new item generation.md.
        /// </summary>
        internal static string SyncInstructionsFileName {
            get {
                return ResourceManager.GetString("SyncInstructionsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Steps to include new item generation.
        /// </summary>
        internal static string SyncInstructionsHeader {
            get {
                return ResourceManager.GetString("SyncInstructionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Changes required in file &apos;{0}&apos;:.
        /// </summary>
        internal static string SyncInstructionsMergeFile {
            get {
                return ResourceManager.GetString("SyncInstructionsMergeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No preview file could be generated, the following changes could not be integrated: .
        /// </summary>
        internal static string SyncInstructionsMergeFileError {
            get {
                return ResourceManager.GetString("SyncInstructionsMergeFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview the changes in: [{0}]({0}).
        /// </summary>
        internal static string SyncInstructionsMergeFilePreview {
            get {
                return ResourceManager.GetString("SyncInstructionsMergeFilePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Modified files:.
        /// </summary>
        internal static string SyncInstructionsModifiedFiles {
            get {
                return ResourceManager.GetString("SyncInstructionsModifiedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To integrate your new item with the existing project apply the following changes: .
        /// </summary>
        internal static string SyncInstructionsModifiedFilesDescription {
            get {
                return ResourceManager.GetString("SyncInstructionsModifiedFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## New files:.
        /// </summary>
        internal static string SyncInstructionsNewFiles {
            get {
                return ResourceManager.GetString("SyncInstructionsNewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy and add the following files to your project:.
        /// </summary>
        internal static string SyncInstructionsNewFilesDescription {
            get {
                return ResourceManager.GetString("SyncInstructionsNewFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find all referenced files: {0}.
        /// </summary>
        internal static string SyncInstructionsTempFolder {
            get {
                return ResourceManager.GetString("SyncInstructionsTempFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Unchanged files:.
        /// </summary>
        internal static string SyncInstructionsUnchangedFiles {
            get {
                return ResourceManager.GetString("SyncInstructionsUnchangedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These files already exist in your project, no action is necessary:.
        /// </summary>
        internal static string SyncInstructionsUnchangedFilesDescription {
            get {
                return ResourceManager.GetString("SyncInstructionsUnchangedFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Conflicting files:.
        /// </summary>
        internal static string SyncSummaryConflictingFiles {
            get {
                return ResourceManager.GetString("SyncSummaryConflictingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These files already exist in your project and were also generated as part of the new item.
        ///Please compare and make sure everything is in the right place..
        /// </summary>
        internal static string SyncSummaryConflictingFilesDescription {
            get {
                return ResourceManager.GetString("SyncSummaryConflictingFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following changes have been incorporated into your project:.
        /// </summary>
        internal static string SyncSummaryDescription {
            get {
                return ResourceManager.GetString("SyncSummaryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Failed changes in files:.
        /// </summary>
        internal static string SyncSummaryFailedMerges {
            get {
                return ResourceManager.GetString("SyncSummaryFailedMerges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merges in the following files failed:.
        /// </summary>
        internal static string SyncSummaryFailedMergesDescription {
            get {
                return ResourceManager.GetString("SyncSummaryFailedMergesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerationSummary.md.
        /// </summary>
        internal static string SyncSummaryFileName {
            get {
                return ResourceManager.GetString("SyncSummaryFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Generation summary.
        /// </summary>
        internal static string SyncSummaryHeader {
            get {
                return ResourceManager.GetString("SyncSummaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Changes in file &apos;{0}&apos;:.
        /// </summary>
        internal static string SyncSummaryMergeFile {
            get {
                return ResourceManager.GetString("SyncSummaryMergeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following changes could not be integrated:.
        /// </summary>
        internal static string SyncSummaryMergeFileError {
            get {
                return ResourceManager.GetString("SyncSummaryMergeFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the final result: [{0}]({0}).
        /// </summary>
        internal static string SyncSummaryMergeFilePreview {
            get {
                return ResourceManager.GetString("SyncSummaryMergeFilePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Modified files:.
        /// </summary>
        internal static string SyncSummaryModifiedFiles {
            get {
                return ResourceManager.GetString("SyncSummaryModifiedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following changes have been applied:.
        /// </summary>
        internal static string SyncSummaryModifiedFilesDescription {
            get {
                return ResourceManager.GetString("SyncSummaryModifiedFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## New files:.
        /// </summary>
        internal static string SyncSummaryNewFiles {
            get {
                return ResourceManager.GetString("SyncSummaryNewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These files have been added to your project..
        /// </summary>
        internal static string SyncSummaryNewFilesDescription {
            get {
                return ResourceManager.GetString("SyncSummaryNewFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectFile.
        /// </summary>
        internal static string SyncSummaryProjectFile {
            get {
                return ResourceManager.GetString("SyncSummaryProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find all referenced files: {0}.
        /// </summary>
        internal static string SyncSummaryTempFolder {
            get {
                return ResourceManager.GetString("SyncSummaryTempFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp.
        /// </summary>
        internal static string SyncSummaryTempGenerationFile {
            get {
                return ResourceManager.GetString("SyncSummaryTempGenerationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates extracted to.
        /// </summary>
        internal static string TemplatesContentExtractedToString {
            get {
                return ResourceManager.GetString("TemplatesContentExtractedToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The templates can&apos;t be extracted..
        /// </summary>
        internal static string TemplatesSourceExtractContentMessage {
            get {
                return ResourceManager.GetString("TemplatesSourceExtractContentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to purge old content..
        /// </summary>
        internal static string TemplatesSynchronizationPurgeContentAsyncMessage {
            get {
                return ResourceManager.GetString("TemplatesSynchronizationPurgeContentAsyncMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid digital signatures in &apos;{0}&apos;. The content has been tampered or the certificate is not present, not valid or not allowed.  Unable to continue..
        /// </summary>
        internal static string TemplatexExtractMessage {
            get {
                return ResourceManager.GetString("TemplatexExtractMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} certificates matching the thumbprint {1} in the store {2}.
        /// </summary>
        internal static string TemplatexFindCertificateFoundMessage {
            get {
                return ResourceManager.GetString("TemplatexFindCertificateFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate found does not have private key..
        /// </summary>
        internal static string TemplatexFindCertificateNoPkMessage {
            get {
                return ResourceManager.GetString("TemplatexFindCertificateNoPkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one certificate found matching the thumbrint. Returning the first one..
        /// </summary>
        internal static string TemplatexFindCertificateNotOneMessage {
            get {
                return ResourceManager.GetString("TemplatexFindCertificateNotOneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified source &apos;{0}&apos; is invalid, the file does not exist, or the folder is empty..
        /// </summary>
        internal static string TemplatexGetSourceFilesMessage {
            get {
                return ResourceManager.GetString("TemplatexGetSourceFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No certificate found matching the thumbrint {0}. Searched on CurrentUser/My and LocalMachine/My stores..
        /// </summary>
        internal static string TemplatexLoadCertMessage {
            get {
                return ResourceManager.GetString("TemplatexLoadCertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate with thumbprint {0} can&apos;t be found in CurrentUser/My or LocalMachine/My..
        /// </summary>
        internal static string TemplatexPackAndSignMessage {
            get {
                return ResourceManager.GetString("TemplatexPackAndSignMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error signing package..
        /// </summary>
        internal static string TemplatexSignAllPartsMessage {
            get {
                return ResourceManager.GetString("TemplatexSignAllPartsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package signature certificate validation not passed..
        /// </summary>
        internal static string TemplatexValidatePackageCertificatesMessage {
            get {
                return ResourceManager.GetString("TemplatexValidatePackageCertificatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate &apos;{0}&apos; verification finished with status &apos;{1}&apos;.
        /// </summary>
        internal static string TemplatexVerifyCertificateMessage {
            get {
                return ResourceManager.GetString("TemplatexVerifyCertificateMessage", resourceCulture);
            }
        }
    }
}
