//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Templates.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Templates.Core.Resources.StringRes", typeof(StringRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Message.
        /// </summary>
        public static string AdditionalMessageString {
            get {
                return ResourceManager.GetString("AdditionalMessageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addtional Exception Info.
        /// </summary>
        public static string AddtionalExceptionInfoString {
            get {
                return ResourceManager.GetString("AddtionalExceptionInfoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly File Version.
        /// </summary>
        public static string AssemblyFileVersionString {
            get {
                return ResourceManager.GetString("AssemblyFileVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query &quot;{0}&quot; is not valid. Allowed operators are &apos;==&apos; or &apos;!=&apos;. Multiple conditions are separated by &apos;&amp;&apos;..
        /// </summary>
        public static string CompositionQueryParseMessage {
            get {
                return ResourceManager.GetString("CompositionQueryParseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file loaded.
        /// </summary>
        public static string ConfigurationFileLoadedString {
            get {
                return ResourceManager.GetString("ConfigurationFileLoadedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current content expiration.
        /// </summary>
        public static string CurrentContentExpirationString {
            get {
                return ResourceManager.GetString("CurrentContentExpirationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular dependency detected on template {0} with {1}..
        /// </summary>
        public static string ErrorDependencyCircularReference {
            get {
                return ResourceManager.GetString("ErrorDependencyCircularReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency template {0} not found on user selection..
        /// </summary>
        public static string ErrorDependencyMissing {
            get {
                return ResourceManager.GetString("ErrorDependencyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid dependency item {0}. Dependencies have to be configured as multipleInstance = false..
        /// </summary>
        public static string ErrorDependencyMultipleInstance {
            get {
                return ResourceManager.GetString("ErrorDependencyMultipleInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency template {0} not found for framework {1} and platform {2}..
        /// </summary>
        public static string ErrorDependencyNotFound {
            get {
                return ResourceManager.GetString("ErrorDependencyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid dependency item {0}. Dependency items must be of type Page or Feature..
        /// </summary>
        public static string ErrorDependencyType {
            get {
                return ResourceManager.GetString("ErrorDependencyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template &apos;{0}&apos;, name: &apos;{1}&apos;, reason: &apos;{2}&apos;.
        /// </summary>
        public static string ErrorGenerating {
            get {
                return ResourceManager.GetString("ErrorGenerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout template {0} not found for framework {1} and platform {2}..
        /// </summary>
        public static string ErrorLayoutNotFound {
            get {
                return ResourceManager.GetString("ErrorLayoutNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid layout item {0}. Layout items must be of type Page or Feature..
        /// </summary>
        public static string ErrorLayoutType {
            get {
                return ResourceManager.GetString("ErrorLayoutType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is a reserved name. Please choose a different name and try again..
        /// </summary>
        public static string ErrorProjectReservedName {
            get {
                return ResourceManager.GetString("ErrorProjectReservedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid name. Project name can&apos;t start with &quot;{1}&quot;..
        /// </summary>
        public static string ErrorProjectStartsWith {
            get {
                return ResourceManager.GetString("ErrorProjectStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid project name.
        /// </summary>
        public static string ErrorTitleInvalidProjectName {
            get {
                return ResourceManager.GetString("ErrorTitleInvalidProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception tracking telemetry during generation..
        /// </summary>
        public static string ErrorTrackTelemetryException {
            get {
                return ResourceManager.GetString("ErrorTrackTelemetryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve platform..
        /// </summary>
        public static string ErrorUnableResolvePlatform {
            get {
                return ResourceManager.GetString("ErrorUnableResolvePlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Info.
        /// </summary>
        public static string ExceptionInfoString {
            get {
                return ResourceManager.GetString("ExceptionInfoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find project file for item {0}.
        /// </summary>
        public static string ExceptionProjectNotFound {
            get {
                return ResourceManager.GetString("ExceptionProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string ExceptionString {
            get {
                return ResourceManager.GetString("ExceptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Tracked.
        /// </summary>
        public static string ExceptionTrackedString {
            get {
                return ResourceManager.GetString("ExceptionTrackedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file &apos;{0}&apos; to include the following changes. Please review the code blocks to include the changes manually where required in your project. Related Template: &apos;{1}&apos;..
        /// </summary>
        public static string FailedMergePostActionFileNotFound {
            get {
                return ResourceManager.GetString("FailedMergePostActionFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The style with key &apos;{0}&apos; is already defined with different value or elements in this file. Please review the styles to include the changes manually where required in your project. Related Template: &apos;{1}&apos;..
        /// </summary>
        public static string FailedMergePostActionKeyAlreadyDefined {
            get {
                return ResourceManager.GetString("FailedMergePostActionKeyAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the expected line `{0}` in file &apos;{1}&apos;. Please merge the content from the postaction file manually. Related Template: &apos;{2}&apos;..
        /// </summary>
        public static string FailedMergePostActionLineNotFound {
            get {
                return ResourceManager.GetString("FailedMergePostActionLineNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File `{0}` has encoding &amp;apos;{1}&amp;apos; while file `{2}` has encoding &amp;apos;{3}&amp;apos; please ensure both encodings are the same..
        /// </summary>
        public static string FailedMergePostActionMismatchedEncoding {
            get {
                return ResourceManager.GetString("FailedMergePostActionMismatchedEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove readonly protection from file {0}.
        /// </summary>
        public static string FsEnsureFileEditableException {
            get {
                return ResourceManager.GetString("FsEnsureFileEditableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} can&apos;t be copied to {1}. Error: {2}.
        /// </summary>
        public static string FsSafeCopyFileMessage {
            get {
                return ResourceManager.GetString("FsSafeCopyFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder {0} can&apos;t be delete. Error: {1}.
        /// </summary>
        public static string FsSafeDeleteDirectoryMessage {
            get {
                return ResourceManager.GetString("FsSafeDeleteDirectoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} can&apos;t be delete. Error: {1}.
        /// </summary>
        public static string FsSafeDeleteFileMessage {
            get {
                return ResourceManager.GetString("FsSafeDeleteFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder {0} can&apos;t be moved to {1}. Error: {2}.
        /// </summary>
        public static string FsSafeMoveDirectoryMessage {
            get {
                return ResourceManager.GetString("FsSafeMoveDirectoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} can&apos;t be moved to {1}. Error: {2}.
        /// </summary>
        public static string FsSafeMoveFileMessage {
            get {
                return ResourceManager.GetString("FsSafeMoveFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder {0} can&apos;t be rename. Error: {1}.
        /// </summary>
        public static string FsSafeRenameDirectoryMessage {
            get {
                return ResourceManager.GetString("FsSafeRenameDirectoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error initializating GenContext..
        /// </summary>
        public static string GenContextBootstrapError {
            get {
                return ResourceManager.GetString("GenContextBootstrapError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no context for the current gen execution, call Current_set first.
        /// </summary>
        public static string GenContextCurrentInvalidOperationMessage {
            get {
                return ResourceManager.GetString("GenContextCurrentInvalidOperationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating certificate..
        /// </summary>
        public static string GenerateTestCertificatePostActionExecute {
            get {
                return ResourceManager.GetString("GenerateTestCertificatePostActionExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log started.
        /// </summary>
        public static string LogStartedString {
            get {
                return ResourceManager.GetString("LogStartedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Recommended Markdown viewer: [Markdown Editor VS Extension](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.MarkdownEditor)*.
        /// </summary>
        public static string MarkdownHeader {
            get {
                return ResourceManager.GetString("MarkdownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no merge target for file &apos;{0}&apos;. Related Template: &apos;{1}&apos;..
        /// </summary>
        public static string MergeFileNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("MergeFileNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0} not found in file &apos;{1}&apos;. Related Template: &apos;{2}&apos;..
        /// </summary>
        public static string MergeLineNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("MergeLineNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to infer a name. Too many iterations.
        /// </summary>
        public static string NamingInferMessage {
            get {
                return ResourceManager.GetString("NamingInferMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package certificate.
        /// </summary>
        public static string PackageCertificateString {
            get {
                return ResourceManager.GetString("PackageCertificateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing &apos;{0}&apos;. Ignoring the error as Continue on Error is enabled. Related template: {1}..
        /// </summary>
        public static string PostActionContinuerOnErrorWarning {
            get {
                return ResourceManager.GetString("PostActionContinuerOnErrorWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing &apos;{0}&apos;. Related template: {1}..
        /// </summary>
        public static string PostActionException {
            get {
                return ResourceManager.GetString("PostActionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PostAction.ActionId &apos;{0}&apos; defined in the template does not match with the expected class ActionId &apos;{1}&apos;. Can&apos;t continue. Related template: {2}..
        /// </summary>
        public static string PostActionIdsNotMatchError {
            get {
                return ResourceManager.GetString("PostActionIdsNotMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string PostActionRelatedNone {
            get {
                return ResourceManager.GetString("PostActionRelatedNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading from {0}. Internet connection is required to download template updates..
        /// </summary>
        public static string RemoteTemplatesSourceDownloadContentKoErrorMessage {
            get {
                return ResourceManager.GetString("RemoteTemplatesSourceDownloadContentKoErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates content can&apos;t be downloaded right now, we will try it later..
        /// </summary>
        public static string RemoteTemplatesSourceDownloadContentKoInfoMessage {
            get {
                return ResourceManager.GetString("RemoteTemplatesSourceDownloadContentKoInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates content downloaded to {0} from {1}..
        /// </summary>
        public static string RemoteTemplatesSourceDownloadContentOkMessage {
            get {
                return ResourceManager.GetString("RemoteTemplatesSourceDownloadContentOkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error syncing templates. Status:.
        /// </summary>
        public static string RepositorySynchronizationExceptionMessage {
            get {
                return ResourceManager.GetString("RepositorySynchronizationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating &apos;{0}&apos; feature ....
        /// </summary>
        public static string StatusBarGeneratingFeatureMessage {
            get {
                return ResourceManager.GetString("StatusBarGeneratingFeatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating &apos;{0}&apos; page ....
        /// </summary>
        public static string StatusBarGeneratingPageMessage {
            get {
                return ResourceManager.GetString("StatusBarGeneratingPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating project &apos;{0}&apos;....
        /// </summary>
        public static string StatusBarGeneratingProjectMessage {
            get {
                return ResourceManager.GetString("StatusBarGeneratingProjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening generated files ....
        /// </summary>
        public static string StatusOpeningItems {
            get {
                return ResourceManager.GetString("StatusOpeningItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps to include new item generation.md.
        /// </summary>
        public static string SyncInstructionsFileName {
            get {
                return ResourceManager.GetString("SyncInstructionsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Conflicting files:
        ///These files already exist in your project and were also generated as part of the new item.
        ///Please compare and make sure everything is in the right place:
        ///{0}.
        /// </summary>
        public static string SyncInstructionsSectionConflictingFiles {
            get {
                return ResourceManager.GetString("SyncInstructionsSectionConflictingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Modified files:
        ///To integrate your new item with the existing project apply the following changes:
        ///{0}.
        /// </summary>
        public static string SyncInstructionsSectionModifiedFiles {
            get {
                return ResourceManager.GetString("SyncInstructionsSectionModifiedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## New files:
        ///Copy and add the following files to your project:
        ///{0}.
        /// </summary>
        public static string SyncInstructionsSectionNewFiles {
            get {
                return ResourceManager.GetString("SyncInstructionsSectionNewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Unchanged files:
        ///These files already exist in your project, no action is necessary:
        ///{0}.
        /// </summary>
        public static string SyncInstructionsSectionUnchangedFiles {
            get {
                return ResourceManager.GetString("SyncInstructionsSectionUnchangedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Recommended Markdown viewer: [Markdown Editor VS Extension](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.MarkdownEditor)*
        ///
        ///# Steps to include new item generation
        ///Please follow the instructions to include the new item into you project:
        ///
        ///You can find all referenced files in the temporary generation folder: {0}
        ///
        ///{1}
        ///{2}
        ///{3}
        ///{4}.
        /// </summary>
        public static string SyncInstructionsTemplate {
            get {
                return ResourceManager.GetString("SyncInstructionsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///### Changes required in file &apos;{0}&apos;:
        ///{1}
        ///Preview the changes in: {2}.
        /// </summary>
        public static string SyncInstructionsTemplateModifiedFile {
            get {
                return ResourceManager.GetString("SyncInstructionsTemplateModifiedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerationSummary.md.
        /// </summary>
        public static string SyncSummaryFileName {
            get {
                return ResourceManager.GetString("SyncSummaryFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectFile.
        /// </summary>
        public static string SyncSummaryProjectFile {
            get {
                return ResourceManager.GetString("SyncSummaryProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Conflicting files:
        ///These files already exist in your project and were also generated as part of the new item.
        ///Please compare and make sure everything is in the right place.
        ///{0}.
        /// </summary>
        public static string SyncSummarySectionConflictingFiles {
            get {
                return ResourceManager.GetString("SyncSummarySectionConflictingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Failed changes in files:
        ///Merges in the following files failed:
        ///{0}.
        /// </summary>
        public static string SyncSummarySectionFailedMergeFiles {
            get {
                return ResourceManager.GetString("SyncSummarySectionFailedMergeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Modified files:
        ///The following changes have been applied:
        ///{0}.
        /// </summary>
        public static string SyncSummarySectionModifiedFiles {
            get {
                return ResourceManager.GetString("SyncSummarySectionModifiedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## New files:
        ///These files have been added to your project.
        ///{0}.
        /// </summary>
        public static string SyncSummarySectionNewFiles {
            get {
                return ResourceManager.GetString("SyncSummarySectionNewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp.
        /// </summary>
        public static string SyncSummaryTempGenerationFile {
            get {
                return ResourceManager.GetString("SyncSummaryTempGenerationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Recommended Markdown viewer: [Markdown Editor VS Extension](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.MarkdownEditor)*
        ///
        ///# Generation summary
        ///The following changes have been incorporated into your project:
        ///
        ///You can find the files from the generation in the temporary generation folder: {0}
        ///
        ///{1}
        ///{2}
        ///{3}
        ///{4}.
        /// </summary>
        public static string SyncSummaryTemplate {
            get {
                return ResourceManager.GetString("SyncSummaryTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///### Changes in file &apos;{0}&apos;:
        ///The following changes could not be integrated: {2}
        ///{1}.
        /// </summary>
        public static string SyncSummaryTemplateFailedMerges {
            get {
                return ResourceManager.GetString("SyncSummaryTemplateFailedMerges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///### Changes in file &apos;{0}&apos;:
        ///See the final result: {2}
        ///
        ///{1}.
        /// </summary>
        public static string SyncSummaryTemplateModifiedFile {
            get {
                return ResourceManager.GetString("SyncSummaryTemplateModifiedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid digital signatures in &apos;{0}&apos;. The content has been tampered or the certificate is not present, not valid or not allowed.  Unable to continue..
        /// </summary>
        public static string TemplatePackageExtractMessage {
            get {
                return ResourceManager.GetString("TemplatePackageExtractMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} certificates matching the thumbprint {1} in the store {2}.
        /// </summary>
        public static string TemplatePackageFindCertificateFoundMessage {
            get {
                return ResourceManager.GetString("TemplatePackageFindCertificateFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate found does not have private key..
        /// </summary>
        public static string TemplatePackageFindCertificateNoPkMessage {
            get {
                return ResourceManager.GetString("TemplatePackageFindCertificateNoPkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one certificate found matching the thumbrint. Returning the first one..
        /// </summary>
        public static string TemplatePackageFindCertificateNotOneMessage {
            get {
                return ResourceManager.GetString("TemplatePackageFindCertificateNotOneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified source &apos;{0}&apos; is invalid, the file does not exist, or the folder is empty..
        /// </summary>
        public static string TemplatePackageGetSourceFilesMessage {
            get {
                return ResourceManager.GetString("TemplatePackageGetSourceFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No certificate found matching the thumbrint {0}. Searched on CurrentUser/My and LocalMachine/My stores..
        /// </summary>
        public static string TemplatePackageLoadCertMessage {
            get {
                return ResourceManager.GetString("TemplatePackageLoadCertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate with thumbprint {0} can&apos;t be found in CurrentUser/My or LocalMachine/My..
        /// </summary>
        public static string TemplatePackagePackAndSignMessage {
            get {
                return ResourceManager.GetString("TemplatePackagePackAndSignMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error signing package..
        /// </summary>
        public static string TemplatePackageSignAllPartsMessage {
            get {
                return ResourceManager.GetString("TemplatePackageSignAllPartsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package signature certificate validation not passed..
        /// </summary>
        public static string TemplatePackageValidatePackageCertificatesMessage {
            get {
                return ResourceManager.GetString("TemplatePackageValidatePackageCertificatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate &apos;{0}&apos; verification finished with status &apos;{1}&apos;.
        /// </summary>
        public static string TemplatePackageVerifyCertificateMessage {
            get {
                return ResourceManager.GetString("TemplatePackageVerifyCertificateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates extracted to.
        /// </summary>
        public static string TemplatesContentExtractedToString {
            get {
                return ResourceManager.GetString("TemplatesContentExtractedToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading source config file..
        /// </summary>
        public static string TemplatesSourceErrorLoadingConfigFileMessage {
            get {
                return ResourceManager.GetString("TemplatesSourceErrorLoadingConfigFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The templates can&apos;t be extracted..
        /// </summary>
        public static string TemplatesSourceExtractContentMessage {
            get {
                return ResourceManager.GetString("TemplatesSourceExtractContentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates local path is empty..
        /// </summary>
        public static string TemplatesSourceLocalPathEmptyMessage {
            get {
                return ResourceManager.GetString("TemplatesSourceLocalPathEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error acquiring content..
        /// </summary>
        public static string TemplatesSynchronizationErrorAcquiring {
            get {
                return ResourceManager.GetString("TemplatesSynchronizationErrorAcquiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading source config file..
        /// </summary>
        public static string TemplatesSynchronizationErrorDownloadingConfig {
            get {
                return ResourceManager.GetString("TemplatesSynchronizationErrorDownloadingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error extracting installed templates content...
        /// </summary>
        public static string TemplatesSynchronizationErrorExtracting {
            get {
                return ResourceManager.GetString("TemplatesSynchronizationErrorExtracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating templates content..
        /// </summary>
        public static string TemplatesSynchronizationErrorUpdating {
            get {
                return ResourceManager.GetString("TemplatesSynchronizationErrorUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to purge old content..
        /// </summary>
        public static string TemplatesSynchronizationPurgeContentAsyncMessage {
            get {
                return ResourceManager.GetString("TemplatesSynchronizationPurgeContentAsyncMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other instance is syncing templates... Waiting 5 seconds..
        /// </summary>
        public static string TemplatesSynchronizationWaitingOtherInstanceMessage {
            get {
                return ResourceManager.GetString("TemplatesSynchronizationWaitingOtherInstanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating the instance locking file..
        /// </summary>
        public static string TemplatesSynchronizationWarnCreatingLockFileMessage {
            get {
                return ResourceManager.GetString("TemplatesSynchronizationWarnCreatingLockFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting the instance locking file..
        /// </summary>
        public static string TemplatesSynchronizationWarnDeletingLockFileMessage {
            get {
                return ResourceManager.GetString("TemplatesSynchronizationWarnDeletingLockFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading the instance locking file..
        /// </summary>
        public static string TemplatesSynchronizationWarnReadingLockFileMessage {
            get {
                return ResourceManager.GetString("TemplatesSynchronizationWarnReadingLockFileMessage", resourceCulture);
            }
        }
    }
}
