name: $(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
    - main
  paths:
    include:
      - code
    exclude:
      - code/TemplateStudioForWinUICs
      - code/TemplateStudioForWinUICpp
      - code/TemplateStudioForWPF
      - code/src/ProjectTemplates/WinUI/Cs
      - code/src/ProjectTemplates/WinUI/Cpp
      - code/src/ProjectTemplates/WPF
      - code/test/TemplateStudioForWinUICs.Tests
      - code/test/TemplateStudioForWinUICpp.Tests
      - code/test/TemplateStudioForWPF.Tests
  batch: True

pr:
  branches:
    include:
      - main
  paths:
    include:
      - code
    exclude:
      - code/TemplateStudioForWinUICs
      - code/TemplateStudioForWinUICpp
      - code/TemplateStudioForWPF
      - code/src/ProjectTemplates/WinUI/Cs
      - code/src/ProjectTemplates/WinUI/Cpp
      - code/src/ProjectTemplates/WPF
      - code/test/TemplateStudioForWinUICs.Tests
      - code/test/TemplateStudioForWinUICpp.Tests
      - code/test/TemplateStudioForWPF.Tests

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

variables:
- name: NUGET.PLUGIN.HANDSHAKE.TIMEOUT.IN.SECONDS
  value: 20
- name: NUGET.PLUGIN.REQUEST.TIMEOUT.IN.SECONDS
  value: 20

jobs:
- template: templates/build.yml
  parameters:
    Moniker: UWP
    BuildConfiguration: ReleaseUWP
    BuildPlatform: Any CPU

- template: templates/test.yml
  parameters:
    Moniker: UWP
    BuildConfiguration: DebugUWP
    BuildPlatform: Any CPU
    Group: MinimumUWP