name: $(date:yyyyMMdd)$(rev:.r)

trigger: none

pr: none

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

jobs:
- job: Build
  displayName: Build
  timeoutInMinutes: 240

  strategy:
    matrix:
      WinUICs:
        Moniker: WinUICs
        BuildConfiguration: ReleaseWinUICs
        BuildPlatform: Any CPU
      WinUICpp:
        Moniker: WinUICpp
        BuildConfiguration: ReleaseWinUICpp
        BuildPlatform: Any CPU
      WPF:
        Moniker: WPF
        BuildConfiguration: ReleaseWPF
        BuildPlatform: Any CPU
      UWP:
        Moniker: UWP
        BuildConfiguration: ReleaseUWP
        BuildPlatform: Any CPU

  pool:
    vmImage: windows-2022

  steps:
  - checkout: self
    clean: true
    submodules: recursive

  - task: NuGetToolInstaller@1
    displayName: Use NuGet
    inputs:
      checkLatest: true

  - task: NuGetCommand@2
    displayName: NuGet restore
    inputs:
      solution: code/TemplateStudio.sln

  - task: PowerShell@2
    displayName: Update VSIX Configuration
    inputs:
      targetType: inline
      script: |
        (Get-Content $(Build.SourcesDirectory)\code\TemplateStudioFor$(Moniker)\CoreTemplateStudio.config.json) -replace '<RemoteTelemetryKey>', '$(RemoteTelemetryKey)' |
        (Set-Content $(Build.SourcesDirectory)\code\TemplateStudioFor$(Moniker)\CoreTemplateStudio.config.json)
      pwsh: true

  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: code/TemplateStudio.sln
      vsVersion: 17.0
      msbuildArgs: /p:DeployExtension=false
      configuration: $(BuildConfiguration)
      platform: $(BuildPlatform)
      clean: true

  - task: ComponentGovernanceComponentDetection@0
    displayName: Component Detection

  - task: PowerShell@1
    displayName: Extract Unsigned Files from VSIX
    inputs:
      scriptName: _build/CodeSign_ExtractFilesToSign.ps1
      arguments: -vsixFilePath $(Build.SourcesDirectory)\code\TemplateStudioFor$(Moniker)\bin\$(BuildConfiguration)\TemplateStudioFor$(Moniker).vsix -outputPath $(Build.ArtifactStagingDirectory)\signing\TemplateStudioFor$(Moniker)

  - task: EsrpCodeSigning@1
    displayName: Sign Assemblies
    inputs:
      ConnectedServiceName: ESRP CodeSigning - Template Studio
      FolderPath: $(Build.ArtifactStagingDirectory)\signing\TemplateStudioFor$(Moniker)
      Pattern: TemplateStudioFor$(Moniker).dll,SharedResources.dll,WriteableBitmapEx.Wpf.dll
      signConfigType: inlineSignParams
      inlineOperation: >-
        [
          {
            "KeyCode" : "CP-230012",
            "OperationCode" : "SigntoolSign",
            "Parameters" : {
              "OpusName" : "Microsoft",
              "OpusInfo" : "http://www.microsoft.com",
              "FileDigest" : "/fd \"SHA256\"",
              "PageHash" : "/NPH",
              "TimeStamp" : "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            },
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
          },
          {
            "KeyCode" : "CP-230012",
            "OperationCode" : "SigntoolVerify",
            "Parameters" : {},
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
          }
        ]

  - task: EsrpCodeSigning@1
    displayName: Sign JS
    inputs:
      ConnectedServiceName: ESRP CodeSigning - Template Studio
      FolderPath: $(Build.ArtifactStagingDirectory)\signing\TemplateStudioFor$(Moniker)\Assets\Html\min\vs
      Pattern: '*.js'
      signConfigType: inlineSignParams
      inlineOperation: >-
        [
          {
            "KeyCode" : "CP-230012",
            "OperationCode" : "SigntoolSign",
            "Parameters" : {
              "OpusName" : "Microsoft",
              "OpusInfo" : "http://www.microsoft.com",
              "FileDigest" : "/fd \"SHA256\"",
              "PageHash" : "/NPH",
              "TimeStamp" : "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            },
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
          },
          {
            "KeyCode" : "CP-230012",
            "OperationCode" : "SigntoolVerify",
            "Parameters" : {},
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
          }
        ]

  - task: PowerShell@1
    displayName: Include Signed Files in VSIX
    inputs:
      scriptName: _build/CodeSign_IncludeSignedFiles.ps1
      arguments: -vsixFilePath $(Build.SourcesDirectory)\code\TemplateStudioFor$(Moniker)\bin\$(BuildConfiguration)\TemplateStudioFor$(Moniker).vsix -inputPath $(Build.ArtifactStagingDirectory)\signing\TemplateStudioFor$(Moniker)

  - task: EsrpCodeSigning@1
    displayName: Sign VSIX
    inputs:
      ConnectedServiceName: ESRP CodeSigning - Template Studio
      FolderPath: $(Build.SourcesDirectory)\code\TemplateStudioFor$(Moniker)\bin\$(BuildConfiguration)\
      Pattern: TemplateStudioFor$(Moniker).vsix
      signConfigType: inlineSignParams
      inlineOperation: >-
        [
          {
            "KeyCode" : "CP-233016",
            "OperationCode" : "OpcSign",
            "Parameters" : {
                "FileDigest" : "/fd SHA256"
            },
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
          },
          {
            "KeyCode" : "CP-233016",
            "OperationCode" : "OpcVerify",
            "Parameters" : {},
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
          }
        ]

  - task: CopyFiles@1
    displayName: Copy Artifacts
    condition: succeededOrFailed()
    inputs:
      SourceFolder: $(Build.SourcesDirectory)
      Contents: '**\bin\$(BuildConfiguration)\**'
      TargetFolder: $(Build.ArtifactStagingDirectory)

  - task: CopyFiles@1
    displayName: Aggregate VSIX Artifacts
    condition: succeededOrFailed()
    inputs:
      SourceFolder: $(Build.SourcesDirectory)
      Contents: '**\bin\$(BuildConfiguration)\**\*.vsix'
      TargetFolder: $(Build.ArtifactStagingDirectory)\vsix
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'