ECHO OFF
ECHO 
ECHO VALUE BEFORE: AGENT_DRIVE=%AGENT_DRIVE%
ECHO VALUE BEFORE: Agent.Drive=%Agent.Drive%

ECHO 
ECHO Setting value...

SET AGENT_DRIVE=%CD:~0,3%
SET Agent.Drive=%CD:~0,3%

ECHO VALUE AFTER: AGENT_DRIVE=%AGENT_DRIVE%
ECHO VALUE AFTER: Agent.Drive=%Agent.Drive%