ECHO OFF
ECHO BEFORE
ECHO AGENT_DRIVE=%AGENT_DRIVE%
ECHO Agent.Drive=%Agent.Drive%

SET AGENT_DRIVE=%CD:~0,3%
SET Agent.Drive=%CD:~0,3%

ECHO AFTER
ECHO AGENT_DRIVE=%AGENT_DRIVE%
ECHO Agent.Drive=%Agent.Drive%