public ShellViewModel(IMenuNavigationService menuNavigationService)
^^^-searchabove-replacebelow-vvv
public ShellViewModel(IMenuNavigationService menuNavigationService, IIdentityService identityService)